### PR TITLE
Balance changes

### PR DESCRIPTION
**Pull request by Maxopoly**
Making enchanting 10 % cheaper, removing iron cost from crates, adding a recipe to make logs from crates and shortening sapling convertion times.

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
Bad bot

**Comment by drjawa** [comment]
CAN ONE OF THE ADMINS VERIFY THIS PATCHCAN ONE OF THE ADMINS VERIFY THIS 
PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH
CAN ONE OF THE ADMINS VERIFY THIS PATCH

**Comment by ProgrammerDan** [comment]
See my comments on internal discussion. Branch bulk_crates_redux and an additional forthcoming to handle code change for crate refund will address compaction "issues".

**Comment by ProgrammerDan** [comment]
Pulls #159 address bulk crates fully. Iron is not removed; a non-renewable needs to stay in the recipe.

To make crates an investment possibility instead of a full loss, see #160 which allows a configurable chance of crate refund on decompaction.

**Comment by Maxopoly** [comment]
Replaced by https://github.com/Civcraft/FactoryMod/pull/161

**Comment by poteat** [comment]
Agree with Dan: Crate costs shouldn't be fully renewable.  Generally speaking, I think Civcraft is easy enough already.

**Pull request closed without merging**
