### PR TITLE
added ds3 to random diamond

### PR DESCRIPTION
**Pull request by hlprimm**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks good.

**Comment by ttk2** [comment]
put it up on Civtest, make a Civtest thread, flag me after someone at least successfully makes it. 

Sorry for delegating, busy today. I will put it up and make the thread myself in a while if I get the chance.

**Comment by hlprimm** [comment]
https://forum.civcraft.co/t/open-for-testing-depth-strider-3-in-diamond-random-enchant/817

**Comment by ProgrammerDan** [comment]
Config on civtest.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Pull request merged**
