### PR TITLE
Better NF Scaling

### PR DESCRIPTION
**Pull request by ribagi**
Original was e^(1/(dis / rad))

It is now e^(1/(dis / rad)) - e + 1

### CODE REVIEW

**Comment by ttk2** [comment]
is this supposed to handle the unreasonable jump at 5000?

**Comment by ribagi** [comment]
Yea, so at 4999m is like 1.0005 times. Compare this to 2.7 times at 4999m.

**Comment by WildWeazel** [comment]
old: http://www.wolframalpha.com/input/?i=e^%285000%2Fx%29
new: http://www.wolframalpha.com/input/?i=e^%285000%2Fx%29+-+e+%2B+1

This will make every factory within an exclusion radius cheaper by a factor of (e-1) or ~172% of base

**Comment by ttk2** [comment]
what new factories would this make cost feasible?

**Comment by WildWeazel** [comment]
If my math is right, anything within 3356-4999 would now be cheaper than what 4999 is currently.
2.7x cost at 3356 vs 4999
5x at 2624 vs 3106
10x at 2031 vs 2171

**Comment by ttk2** [comment]
I am not opposed, just wondering on the impacts .

**Comment by ribagi** [comment]
There is currently only a few empty spots left on the map. After they are used up, then if someone wants to make their own factory, they will be about 2.5k away on average away from any other factory. Not to mention the vectoring that happens, the costs will be more than 5 times, as WildWeazel said.

I do not think there will be a large impact. There will be a few more Nether Factories, but not many more.

**Comment by ttk2** [comment]
Hey this didnt remove multiple overlap cost summing right? 

As in if you are in the range of two factories the cost modifiers they provide are summed correct? You don't just pay for the closest one? Or did it never work like that?

**Comment by erocs** [comment]
I believe it only ever used the closest.

**Comment by WildWeazel** [comment]
This didn't change it, however it works.

**Comment by ttk2** [comment]
very well then, it can go online without hesitation and I can disagree or
agree with however its implemented now.

**Pull request merged**
