### PR TITLE
Delete old anvil fix

### PR DESCRIPTION
**Pull request by jjj5311**
Fix Issues #126

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
If you're going to delete this, be sure to remove the config option and where the config option is read on load.

**Comment by jjj5311** [comment]
damn. Did this within github so i will either have to make another commit or just scrap this pull and make a new one. Any opinion?

**Comment by ProgrammerDan** [comment]
I don't really do much with the github interface -- you can't contribute another commit/alteration?

**Comment by ProgrammerDan** [comment]
Hm, you should be able to check out your repository and switch to branch patch-1 locally, make the additional changes and push. That'll update this pull.

**Comment by jjj5311** [comment]
I can add more commits but its 1 commit per file edit... Appears there is no config option in the config for this anyhow

**Comment by WildWeazel** [comment]
Any commits you make to the same source branch will automatically show up in the pull until it is closed

**Comment by ProgrammerDan** [comment]
@jjj5311 For reference https://github.com/Civcraft/FactoryMod/blob/master/config.yml#L307

**Comment by jjj5311** [comment]
gahh what the hell i am missing everything. 

@WildWeazel I am just worried about the inevitable comment about commit clutter

**Comment by jjj5311** [comment]
Alright so with 3 commits I finally have it lol...

I thought this was going to be a 1 file change.

**Comment by ProgrammerDan** [comment]
Time to go local and squash :P

**Comment by jjj5311** [comment]
I will work on that hopefully later tonight/tomorrow

**Comment by ttk2** [comment]
so don't merge yet?

**Comment by ProgrammerDan** [comment]
nah, let him squash the commits.

**Pull request closed without merging**
