### PR TITLE
Adding recipts for prismarine blocks and sea lanterns

### PR DESCRIPTION
**Pull request by Maxopoly**
This would add recipts for all 3 variants of prismarine and sea lanterns to the fancy stonebrick smelter. The balancing is in line with other decorational blocks and basically doubles, what you would get from crafting. Sea lanterns still require 4 crystals per sea lantern, because otherwise it would be possible to get an infinite amount of crystals by destroying lanterns with Fortune 3. Fancy stonebrick smelter seemed like the right factory for it, because aside from the bastion recipt, it's already used only for decorational blocks.

### CODE REVIEW

**Comment by ttk2** [comment]
sound good to me, will run it by the community tomorrow, I think this
should be fine to merge whenever (I am a little worried about things
getting messed up by having the big xp pull merged)

**Comment by ttk2** [comment]
this pull is broken, it seems to have borked the config, did you run it through a validator?

**Comment by ProgrammerDan** [comment]
Shoulda caught this earlier. He's got spaces in his recipe identifiers. That'll fail.

**Comment by ProgrammerDan** [comment]
@ttk2 Check https://github.com/Civcraft/FactoryMod/pull/85

Also agreed to contrib terms for this project, looking good.

**Pull request merged**
