### PR TITLE
Adding compactor create

### PR DESCRIPTION
**Pull request by ProgrammerDan**
line whitespace is off, TODO return and fix, should  create a compactor now though

### CODE REVIEW

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
this is now the version on Civtest.

**Comment by ProgrammerDan** [comment]
Ok, hopefully someone sees the changelog and gets online to test.

**Comment by rourke750** [comment]
@WildWeazel I mentioned this to ttk2 as well but we should stop merging code into the master branch until after it is tested.  To test the code we would just use the jar created via jenkins pull request builder.

**Comment by WildWeazel** [comment]
In general I agree but this is fixing a breaking bug that's already in the master, it's of no use without (at least) this patch.

**Comment by ProgrammerDan** [comment]
For breakfix stuff like this I recommend:

* Drop test build onto civtest and ensure clean startup (e.g. no new regression)

* If passed, then merge. Else, refer back to developer.

**Comment by WildWeazel** [comment]
I'd like to just make that part of the build process: drop the jar into a clean plugins directory, start a server, wait some time and grep for errors/stack traces

**Comment by ProgrammerDan** [comment]
That would be ideal, good use for the VM.

**Comment by WildWeazel** [comment]
we should start tracking these meta-issues somewhere, maybe the civcraft.github.io repo?

**Comment by ttk2** [comment]
Discourse?

**Pull request merged**
