### PR TITLE
Add recipe for red sandstone

### PR DESCRIPTION
**Pull request by Maxopoly**
Adressing https://github.com/Civcraft/FactoryMod/issues/146

### CODE REVIEW

**Comment by ttk2** [comment]
looks fairly straightforward, merging and staging

**Comment by Maxopoly** [comment]
Could you just quickly update civtest, so I can test it to be 100% sure? I ran it through a yaml verifier and it seemed okay, but I just want to be sure.

**Comment by ttk2** [comment]
on civtest

**Comment by Maxopoly** [comment]
Thanks, I quickly tested it and it works, so no objections to staging.

**Pull request merged**
