### PR TITLE
Flooring clay balls to blocks. Added brick_block to kiln.

### PR DESCRIPTION
**Pull request by hlprimm**
Flooring change is just another extension of this pull: https://github.com/Civcraft/FactoryMod/pull/71

Kiln only currently makes individual bricks, which has no other use than making flower pots. Left that individual brick recipe in because I'm not sure if it serves any other purpose. 

However, I added brick_block recipe, which is what most people want when smelting clay for brick.

### CODE REVIEW

**Comment by ttk2** [comment]
Hey thanks for taking the time to make this, this is low priority stuff compared to the mess that's otherwise going on with this repo, so its going to wait until the storm clears up.

**Comment by hlprimm** [comment]
No prob - it's not that urgent! I'll remind people once the whole XP stuff gets sorted out

**Comment by ttk2** [comment]
ok we are pretty close to being able to merge this one, just some final cleanup for the XP stuff, sorry its been in limbo forever.

**Comment by ProgrammerDan** [comment]
@hlprimm should be a clean rebase once we get these last few out of the way, you comfortable doing that or need a walkthrough?

**Comment by hlprimm** [comment]
will need a walkthrough haha ><

**Comment by ProgrammerDan** [comment]
@hlprimm, tbh since the changes here are so few, just checkout a clean copy of master, and redo the work on the new branch, making a new pull request at the end of it. Dealing with a rebase for a dozen lines changes sounds like a recipe for possible intense frustration. However, if you want to give it a go: 

* Pull the latest master branch from Civcraft

* Check out your patch branch: `git checkout patch-2`

* Create a testing branch to test your rebase: `git checkout -b rebase-test`

* Optimistically try: `git rebase master`

* If there are no conflicts, switch back to your prior branch: `git checkout patch-2`

* Do the rebase in that branch.

* Push your changes.

If there are conflicts, you can try to resolve them if you want but it depending on your comfort level might be painful. In that case just delete the temporary rebase testing branch, and follow my initial advice :).

**Comment by hlprimm** [comment]
So I think it's safe to do this now. i'll go ahead and try tonight. Thx @ProgrammerDan !

**Comment by hlprimm** [comment]
Closing this pull since I've updated my repo, this has an old config.yml

**Pull request closed without merging**
