### PR TITLE
Readd smooth double slabs

### PR DESCRIPTION
**Pull request by Maxopoly**
FM version of this pull. 
Making the crafting recipes conform with the config syntax was kinda difficult because there was no documentation on it, I just tried to reconstruct it from the code. @rourke750 are those crafting recipes correct?
Listener is unchanged.

Bonus: 2 config typos I found thanks to Notepad++

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
those bonus changes will make any wall items held in storage no longer work, might not be something we can merge at this point.

**Comment by Maxopoly** [comment]
Hmm, would there be an easy way to convert them? If not I'll just rebase it out.

**Comment by ProgrammerDan** [comment]
uhm, define easy -- probably best to let the typo exist for now.

**Comment by ttk2** [comment]
wall items?

**Comment by ProgrammerDan** [comment]
for bastions -- "Wall" items are lored ink sacs. They were supposed to have durability 4, but long-standing typo means they have durability 0.

**Comment by Maxopoly** [comment]
Okay, I removed those from the pull, could someone put this on civtest?

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
the pull request build seems broken, is this good to merge max?

**Comment by ProgrammerDan** [comment]
They look good to me too, if max is satisfied.

**Comment by Maxopoly** [comment]
If you can merge it without it going on prod yeah go ahead, otherwise not because I cant 100% guarantee without testing that this wont dupe slabs through some weird interaction with bastions/reinforcement.

**Comment by ProgrammerDan** [comment]
Any thoughts on how to test for this?

**Comment by Maxopoly** [comment]
Creation, trying to place without bastion, with bastion, with reinforcement and without. Also with reinforcement in bastionfield so we cant dupe the reinforcement material. Just messing around a bit with it

**Comment by ttk2** [comment]
there should be a build on jenkins that can go on Civtest now.

**Pull request merged**
