### PR TITLE
Update Factory.java

### PR DESCRIPTION
**Pull request by KillerSmurf**
Fixed furnaces not turning off after completing task.

### CODE REVIEW

**Comment by Maxopoly** [comment]
Okay, I really spent a lot of time trying to figure out why this wasn't working and never noticed. Apparently I'm completly retarded.

**Comment by Maxopoly** [comment]
Thanks for your help

**Comment by KillerSmurf** [comment]
@Maxopoly I don't know about you, but when I debug my code I throw in a lot of "System.out.println()" lines, that just have simple messages like "Entered turnFurnaceOff method". So I can see where exactly my code is breaking and where it is ending up. Helps me with dumb issues like this.

**Comment by Maxopoly** [comment]
Yeah, that's what I do too and I have absolutely no idea how I missed this. Let's just pretend it never happened.

**Pull request merged**
