### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by TealNerd**
reverted potato nerf, it shouldn't have happened

### CODE REVIEW

**Comment by ttk2** [comment]
um what?

**Comment by erocs** [comment]
Reduces the number of potatoes needed to produce XP bottles.

      Wood_XP_Bottle_2:
        name: Brew XP Bottles  - 3
        inputs:
          Glass Bottle:
            material: GLASS_BOTTLE
            amount: 5
          Baked Potato:
            material: BAKED_POTATO
            amount: 1280
        outputs:
          Exp Bottle:
            material: EXP_BOTTLE
            amount: 5

**Comment by ttk2** [comment]
so it was a reverse nerf?

**Comment by erocs** [comment]
I believe that's typically called a buff. I don't know if the original potato nerf wasn't intended.

**Comment by ttk2** [comment]
Ok I am losing track here, was the nerf we put online a few days ago
actually a buff?

**Comment by TealNerd** [comment]
no the nerf you put online a few days ago shouldn't have gone online because it makes potatoes produce the least xp per crop even thought they require more infrastructure than the other crops to make xp (two factories instead of just one. more materials to repair that factory. more charcoal to bake the taters, and because there are so many taters you cant use hoppers because they'll bottleneck

**Comment by ttk2** [comment]
who submitted that pull? did they not intend that?

**Comment by TealNerd** [comment]
i think it was greg, he didnt realize they required more infrastructure and when i talked to him about it he agreed but you had already merged. i didn't even realize it was online until two days ago

**Comment by ttk2** [comment]
could we get him in here?

**Comment by TealNerd** [comment]
@Tarenaran

**Comment by Tarenaran** [comment]
The question is, is some additional redstone really worth 1.5x the xp yield?

**Comment by TealNerd** [comment]
yes

**Pull request closed without merging**
