### PR TITLE
Fixed the check for citadel access

### PR DESCRIPTION
**Pull request by spaceFountain**
Originally the conditions for teleporting where as follows: 
    !citadel_enabled or (citadel_enabled and reinforcement != null) or reinforcement.isAccessible
this is the same as
    (!citadel_enabled or citadel_enabled) and (!citadel_enabled or reinforcement!=null) or reinforcement.isAccessible
(!citadel_enabled or citadel_enabled) is obviously true so this becomes
   !citadel_enabled or reinforcement != null or reinforcement.isAccessible

the problem should be obvious here. If reinforcement is ever not null this will go forward regardless of the ability of the player to access the factory.

What I believe was intended was to check if the reinforcement was null and if so just to allow anyone through. To this end I've changed the condition to:
   !citadel_enabled or reinforcement == null or reinforcement.isAccessible

I'm not sure why we were getting some reports of it working properly. Possibly people were just misinformed. This should be a very straight forward change, but I'll try to look into seeing if it works after I've finished with my school work which may take a while

### CODE REVIEW

**Comment by spaceFountain** [comment]
Looking back through the history it seems this was introduced in  e9e0b6cd678a8b8c3f6409b4a1f291bca9b0e65c when things got updated to 1.8. Can I get confirmation that this is the jar that is on the server?

**Comment by ttk2** [comment]
we don't have any 1.8 jars on the server afik, as everything was updated to
citadel 3.0 before that, FactoryMod-1.2.5.jar  is whats online

**Comment by spaceFountain** [comment]
Wops meant to say Citadel 3, but I think that was version 1.3 right @rourke750? At the very least the e9e0b6cd678a8b8c3f6409b4a1f291bca9b0e65c is incorrect as it replaces !isReinfoced with reinforcement!=null. Which is actually the opposite.

**Comment by ttk2** [comment]
well submit a pull with the fix and we can compile against 2.0 and put it
online

**Comment by spaceFountain** [comment]
Sorry just meant to say this fix is needed for Citadel 3. The version
before the commit I linked should be fine.

**Comment by ttk2** [comment]
ah, then we should be all good, we can just push an update now and put it
on the 3.0 testing server

**Comment by spaceFountain** [comment]
I don't see why not. It's a very simple change and the worst it will do is allow for people to teleport when they shouldn't (or vice versa) which is something they can already do.

**Pull request merged**
