### PR TITLE
FactoryMod2

### PR DESCRIPTION
**Pull request by Maxopoly**
I feel like this is ready for master. I copied the current FactoryMod into a new branch called FactoryMod1-Retired.

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by rourke750** [comment]
How does -17000 happen while only +3000 lol.  Anyways, @ttk2 @erocs you guys fine with merging now?

**Comment by Maxopoly** [comment]
To be fair 11.4k of the deleted lines were in the old config and there were some unused scripts that I also removed, but it's probably still less java code now than before, simply because there was a ton of duplicated code before.

**Comment by ProgrammerDan** [comment]
So obvs I haven't been able to review all the changes yet :P

That said, I'm happy to support merging it in so we can move on to testing and refinement.

**Pull request merged**
