### PR TITLE
disable nether decompactors

### PR DESCRIPTION
**Pull request by hlprimm**
https://github.com/Civcraft/FactoryMod/issues/139

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks good, disables creation and disables repair so existing ones will cull once disrepaired. T-minus 6 weeks once this is deployed for full Nether Decompactor removal world-wide.

**Comment by ttk2** [comment]
nice so just merge and stage? testing needed?

**Comment by ProgrammerDan** [comment]
Should need just a verification test, @hlprimm did you do any local test to ensure the recipes showed up as expected for an existing Nether Decompactor?

**Comment by hlprimm** [comment]
@programmerdan I don't have a local spigot  setup :X

**Comment by ProgrammerDan** [comment]
alright no worries, I'll test this out tonight and report back unless one of the other devs wants to grab it.

**Comment by ProgrammerDan** [comment]
Works great, confirmed on Civtest.

Existing factory works as expected, but repair is now "impossible"

**Comment by ttk2** [comment]
staging.

**Pull request merged**
