### PR TITLE
Depth Strider and Aqua Affinity gold armor

### PR DESCRIPTION
**Pull request by Tarenaran**
Adds depth strider enchants 1-3 to gold boot factory enchant list and aqua affinity to gold helmet factory enchant list.

### CODE REVIEW

**Comment by ttk2** [comment]
is this being changed in the enchatning re-balance? I don't think it is.

**Comment by Tarenaran** [comment]
To my knowledge it shouldn't.

**Comment by hlprimm** [comment]
Don't see any problems with this unless we're applying PVP classes to gold armor too, which I don't think is the plan?

**Comment by Tarenaran** [comment]
If gold armor has any PvP use the entire factory system would need to be rebalanced, but having it as just general walking around cheap utility armor is the way it works now

**Comment by ttk2** [comment]
looks like this is good, going to wrap up changelog discussion and then
move forward with it, thanks for the pull .

**Pull request merged**
