### PR TITLE
Added temp repair recipes to New Factories

### PR DESCRIPTION
**Pull request by jezzaindahouse**
It's been too long and factories are dying. Essences aren't out and the whole thing will be looked over anyway so this is no harm/extra effort.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@jezzaindahouse remind me to deploy this if no-one else does in like 4-5 hours

**Comment by Maxopoly** [comment]
Those should definitely get changed for 3.0, but I guess for now they are fine (as long as we remember to change them).

**Comment by ProgrammerDan** [comment]
Yeah... 5 dirt to fully repair seems a mite bit too low for the big time!

**Comment by Maxopoly** [comment]
Not just that, there are like 6 (?) total repair recipes which represent different tiers, scaling with the depth in the tech tree/importance of the factory and that repair recipe is one of the cheaper ones.

**Comment by jezzaindahouse** [comment]
Yea that's fine - we need to look over all of essences and the tier for each factory anyway! Generally everything needs looking over as we were talking about removing repair costs for lower tier factories :)

**Pull request merged**
