### PR TITLE
Update configCivcraft.yml

### PR DESCRIPTION
**Pull request by KillerSmurf**
Added a basic conversion of logs to charcoal in the basic contraption.
Added an advanced conversion of logs to charcoal to the woodprocessor.

Added recipes for burning logs to charcoal (advanced, and basic).

### CODE REVIEW

**Comment by Maxopoly** [comment]
Sign the cla please

**Comment by Maxopoly** [comment]
Also could you make a third tier for the coal smelter?

**Comment by KillerSmurf** [comment]
Yes, I'll do that now.

**Comment by Maxopoly** [comment]
Just make it like 2.5 rate

**Comment by KillerSmurf** [comment]
@Maxopoly Added the expert recipe in.

**Comment by Maxopoly** [comment]
Alright, thanks

**Pull request merged**
