### PR TITLE
Add recipe for new stone variants

### PR DESCRIPTION
**Pull request by Maxopoly**
@ttk2  meowcoolcat said he talked to you and this would be added, if we just put it on a new factory so players dont get it for free. Is this alright?

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
So basically flint and gravel instead of vanilla recipe's quartz requirements?

**Comment by ttk2** [comment]
I guess we could add quartz requirements, not like it makes too much of a difference.

**Comment by Maxopoly** [comment]
Like that?

**Comment by ProgrammerDan** [comment]
Talked to meowcoolcat myself the other night. Meow mentioned that in worlds that spawn these stone variants it is so common that no one crafts them. 

It's a good point i wasn't considering. I guess the amount of quartz should be adjusted relative to how strongly we want to encourage folks to use the new recipe and factory.

**Comment by ttk2** [comment]
if its not horribly unbalanced I say we just go with it as is.

**Comment by Maxopoly** [comment]
It's already relatively cheap, only one recipe requires quartz and that's 16 quartz flakes per stack.

**Comment by ProgrammerDan** [comment]
Alright, I'll toss this on testing.

**Comment by ProgrammerDan** [comment]
Actually @rourke750 can you get the testing server in a state where other testing admins can work on it? Or let me know what black magic you are using currently? :P (read: just attached to tmux, didn't see a server running, but all the world files are locked ...??!!)

**Comment by ttk2** [comment]
roruke is working on sharding, not sure what state its in now.

**Comment by ProgrammerDan** [comment]
Yeah, if he's going to use the main CivTest instance we need to put a halt on all other development until it's back in a consistent state.

My preference would be that he does his setup and initial testing work on a new civtest instance, and leave the active use one in a non-sharding state until he's ready to go live on testing.

**Comment by Maxopoly** [comment]
Yeah the testing server was offline for most of the past few days, I asked black to restart it one time and he said that it had been stuck for quite a while trying to save the world. After he restarted it, it was online for a few hours and then someone killed it again.

**Comment by ttk2** [comment]
actually it looks like jacky might be doing it, no other running servers.

**Comment by ttk2** [comment]
nope, it was better shards glitching out, running again.

**Comment by meowcoolcat** [comment]
Please remove the quartz cost entirely.  It is silly to have this on it AT ALL.  This stuff is as common as dirt is in vanilla spawned worlds.  Most players probably didn't/don't even know it is craftable in vanilla.

Ttk the argument of "if its not horribly unbalanced I say we just go with it as is," is not a good argument.  It is unbalanced enough as it is.  Remove the quartz cost to make it balanced.  Using a finite resource on something that is as common as these stone types is asinine.

**Comment by eldusto** [comment]
Hey this is dsclouse. Are you guys really leaving quartz in the crafting recipe for a block that is as common as dirt in vanilla? Has any thought actually gone into this?

**Comment by ttk2** [comment]
diamonds are 4 times more common in vanilla, does that mean I should give everyone diamonds to make up for the difference? 

There is an argument against quartz, but the vanilla one is pointless, I don't care about vanilla, if I did we would run a vanilla server.

**Comment by meowcoolcat** [comment]
You're argument using diamonds as an example isn't very good. This stone wouldn't be "given away." We are simply pointing out why having quartz (a finite resource) involved in something as common as these stone types (virtually limitless) are in a vanilla generated world.  Had they been around when this map was made/generated they'd be super common too.

Can you please explain why these SHOULD HAVE quartz involved in the recipe other than the "its in the vanilla crafting recipe"? Using the same logic you are using to justify this quartz cost you should change the "Fancy Stone Smelter" then too due to the fact you can make Chiseled Stone Bricks are made using stone brick slabs via Vanilla methods.

**Comment by eldusto** [comment]
It doesn't make much sense to compare something that is 4 times more common to something 1000's of times more common...

meowcoolcat basically said everything I was going to say as well.

**Comment by ProgrammerDan** [comment]
@meowcoolcat I think that crafting recipe is disabled. If it isn't, it's supposed to be. (the Chiseled Stone Bricks one).

I don't care either way tbh. 

I should point out that while flint is definitely more common then quartz, theoretically, it's still pretty uncommon. Adding quartz costs in makes very little difference overall, just that quartz is already used in a bunch of other things. That's the only reason I'd leave it out. 

Perhaps leave the quartz cost in the creation and repair of the factory, but remove it from the actual factory runs?

**Comment by meowcoolcat** [comment]
@ProgrammerDan I was pointing out the Chiseled Bricks as an example of why the logic he is using is flawed.  Quartz should not be involved AT ALL in this factory.  You can get these stone types using a STONE PICK within 5-10 minutes of playing a new world.  Using flint and gravel in this factory gives them an actual use and potentially adds move value to them.

**Comment by ProgrammerDan** [comment]
Maybe pointing out the obvious, but we aren't a new world, nor are we bound to the economic realities of a "new vanilla world". We are an old world, and introducing new blocks *should come at a cost*.

**Comment by eldusto** [comment]
but for what reason?

**Comment by ProgrammerDan** [comment]
Same could be said for adding the recipe to FactoryMod at all, since it's easily craftable ... ??

**Comment by meowcoolcat** [comment]
It is coming at a cost of stone, gravel, and flint.  That is more than enough cost for this stone.

**Comment by jjj5311** [comment]
Gravel and flint are essentially the same resource... Doesn't really make
sense to require them both

**Comment by meowcoolcat** [comment]
@jjj5311 It gives players a use for flint and adds value to it.

**Comment by jjj5311** [comment]
Does the same thing for Quartz

**Comment by meowcoolcat** [comment]
Quartz already has many uses as it is.  Flint currently has 2 MAYBE 3 uses outside of making arrows.

**Comment by ProgrammerDan** [comment]
tbh this isn't worth so much discussion. 

My only real objection is providing a "free" recipe now screws over early adopters. I know, I know, "their loss" -- but at least in my head these recipes always mirrored Vanilla but at 50% improved cost, following the pattern of literally every other factory with a clear vanilla mirror recipe (perhaps excepting Fancy Stone).

Still, put down the pitchforks. 

We're 9 months into 1.8 and no-body should care, I'm surprised to see such an outpouring of emotion in any direction.

**Comment by ProgrammerDan** [comment]
Ok, here's my breakdown.

Vanilla worlds have Diorite, Andesite, and Granite in fields similar to Gravel and Dirt. Their proximate value in the "Minecraft" world writ large is, therefore, low. We can conclude then that whoever decided on the Vanilla recipes was an idiot. Point 1.

We don't care much about Vanilla worlds here. Point 2.

Quartz is well utilized already. Point 3.

Flint is an annoying derivative of Gravel. To get it, break gravel. Repeat until all gravel is Flint. GRIND. Point 4.

Civcraft historically penalizes new cosmetic blocks -- see: Fancy Stone Brick factory -- but does not penalize new cosmetic plants or wood types -- see: Biolab. Point 5.

Civcraft history and precedent is arguable more important than Minecraft's whims. Point 6.

We make everything up as we go, that's the core historic precedent. Point 7.

Which leads me all the way to my conclusion:

We don't care about vanilla recipe. It involves quartz, but arbitrary amounts and with a weird "tech tree" of Diorite as basis, and either add one quartz to get Granite, or one Cobble to get Andesite. Huh? Let's throw that out.

Granite looks like Cobble mixed with Dirt. 

Andesite looks like Cobble mixed with Gravel.

Diorite looks like Cobble mixed with Quartz.

So let's do this:

Granite recipe: 4 stacks cobble, 2 stacks dirt = 4 stacks granite.

Andesite recipe: 4 stacks cobble, 2 stacks gravel = 4 stacks andesite.

Diorite recipe: 4 stacks cobble, half stack quartz = 4 stacks diorite.

And I disable vanilla crafting, b/c it's stupid anyway.

**Comment by Cameleopard** [comment]
Andesite, diorite and granite are common in vanilla, yes, though I think it's an exaggeration to call them as abundant as dirt.  As for why these igneous additions utilize quartz in their crafting recipes, it's because their real-life counterparts (especially granite, which is why it costs the most) contain quartz, as well as a hodgepodge of other minerals.  The problem there is that the crafting recipes only make sense if the distribution of these rocks was similarly balanced against the abundance of quartz. 

But vanilla doesn't matter anyway, whereas precedence does.  Civcraft precedent seems to be an arbitrarily higher or at least just plain arbitrary cost for a cosmetic block in a factory.  The current crafted values of these rocks is around .5d/stack of andesite, 1d/s of diorite and 2d/s of granite.  To my mind, this is already a low cost for a building material, especially when compared to the monstrously extravagant lapis eating fancy stone brick smelter.  I like the idea of a non-flat cost distribution for even cosmetics like these and think whatever the final recipe is should mirror this cost curve.  

Andesite should be cheapest, diorite middle of the road, granite the most expensive (but still cheap, as they already are!).  Cobble and gravel for andesite makes sense, and since it's the cheapest, cool.  Diorite with the quartz cost works out to be around .25d per stack, below where the current crafted andesite cost is at.  The only issue is that granite should be more expensive than that.  Personally I'd be fine with flint in the granite cost.  The extra labor you note for processing gravel would make up the cost difference.  With a fortune 3 shovel every gravel block turns into flint.  Using gravel would give those vast stores of gravel in the nether a use.  Requiring gravel and flint would maybe nudge the enchanted tool market a bit.  So, I propose:

Andesite: 4 stacks cobble, 2 stacks gravel = 4 stacks andesite

Diorite: 4 stacks cobble, half stack nether quartz = 4 stacks diorite

Granite: 4 stacks cobble, 2 stacks flint = 4 stacks granite.

Shit's still arbitrary, cheaper than vanilla crafting (which was already cheap!!!), and makes use of a very abundant but finite resource and maybe will help keep enchanted tool factories running.  Good, bad?

**Comment by ProgrammerDan** [comment]
>  I think it's an exaggeration to call them as abundant as dirt.

It's a quote from the world generation discussion on the Minecraft wiki. They spawn in the exact same types of clusters as dirt and gravel, underground. Dirt is more commonly only because it acts as a surface covering. To be "accurate" I should have made that more clear. Gravel is indeed the direct equivalent in terms of spawn frequency on a "Vanilla" map.

That said, I'm fine with your alteration to my proposal on Granite, although I miss the color equivalency of my proposal (granite looks like fancy dirt to me).

**Comment by ttk2** [comment]
in this thread, overthinking it.

**Comment by ProgrammerDan** [comment]
It's all I've got left, man, it's what moves me.

**Comment by jjj5311** [comment]
god is that funny, perfect response @ttk2

**Comment by Maxopoly** [comment]
We are never going to get a result this way, I changed it to what Dan recommended and I think we should just roll with it.

**Comment by ttk2** [comment]
agreed, what should the changelog blurb be? This is going right online after a quick sanity check on Civtest

**Comment by ProgrammerDan** [comment]
@ttk2 want me to contrib a pull disabling the vanilla crafting recipes? or not worth bothering?

**Comment by Maxopoly** [comment]
If you put it on civtest right now, I could just quickly test it and we throw it on civcraft tomorrow. Just write we added a factory for the new stone types and link to the documentation.

**Comment by ProgrammerDan** [comment]
@Maxopoly @ttk2 It's on Civtest staged. @rourke750 is working on the server ATM so restarts will be frequent. Next time he restarts it should be live.

**Comment by ProgrammerDan** [comment]
Diet_Cola is on civtest right now like a champion testing the changes, creation def works once I gave him the right recipe, hah

**Comment by ttk2** [comment]
sweet, this is staged, putting a thank to him in the changelog .

**Comment by ttk2** [comment]
wait I thought we agreed to keep quartz costs?

**Comment by ProgrammerDan** [comment]
Confusion is king when many voices speak. 

Max pre-emptively changed to my concrete proposal, which apparently @goldmattress doesn't like but didn't bother to chime in on here.

**Comment by ttk2** [comment]
bah, I will just wait for matta to make a proposal and take that.

**Pull request merged**
