### PR TITLE
Slight basic pipe & sorter balancing

### PR DESCRIPTION
**Pull request by Diet-Cola**
Encouraging using pipes & sorters over hoppers

### CODE REVIEW

**Comment by Maxopoly** [comment]
We can make them cheaper, but reducing the cost by factor 8 right away is probably a bit too much, those are still intended to be a mid-late game thing

**Comment by Diet-Cola** [comment]
How would 48 each sound?

**Comment by Maxopoly** [comment]
I keep forgetting that the return from ores is a lot lower now. 48 is okay

**Comment by ttk2** [comment]
can we make the redstone stuff more expensive instead of this cheaper?

**Comment by Maxopoly** [comment]
Well we could disable the crafting recipes and make semi expensive factory recipes. Would probably get a lot of complaints, but could be justified

**Comment by ttk2** [comment]
I think its justified but probably should be discussed elsewhere.

**Pull request merged**
