### PR TITLE
Added deterministic feather falling

### PR DESCRIPTION
**Pull request by TealNerd**
costs 20 emerald blocks to enchant 5 boots, that's 4 emerald blocks per ff enchant

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@goldmattress

I think there was some reason this wasn't included. Paging balancemaster.

**Comment by TealNerd** [comment]
I'm still trying to figure out why we even have a factory where you can choose enchants.

**Comment by hlprimm** [comment]
@TealNerd https://github.com/Civcraft/FactoryMod/pull/130

**Comment by ttk2** [comment]
looks like hlprim tried this before, not sure what happened with it then.

**Comment by TealNerd** [comment]
It looks like he added it to the random enchant factory, this makes it so you can get a sure enchant of feather falling

**Comment by ttk2** [comment]
ok so different pulls, did hlprimms ever get online? I think it did.

**Comment by hlprimm** [comment]
Reasoning behind canceling of my pull was that it should be only in the random enchant factories because that's why people invested in them

**Comment by hlprimm** [comment]
Ask @goldmattress

**Comment by ProgrammerDan** [comment]
Hey @goldmattress I'm assuming this FF4 introduction to deterministic factories is a no go -- please weigh in so I can close or merge, based on your feedback.

**Comment by TealNerd** [comment]
@hlprimm imo that's not a very good reason

**Comment by ProgrammerDan** [comment]
@ttk2 has literally given @goldmattress free reign on economy and game balance, and this is firmly in that domain. It's his call.

**Comment by Goldmattress** [comment]
Ok I'll add it in at a stupid high cost, 50 blocks.

**Comment by rourke750** [comment]
bump

**Comment by Goldmattress** [comment]
@TealNerd change the pull as I said

**Comment by Maxopoly** [comment]
@TealNerd  Are you gonna change this or should it be closed?

**Comment by TealNerd** [comment]
Oh oops didn't see this I'll fix it

**Comment by Maxopoly** [comment]
@TealNerd  I'll close this, make a new pull request if you are ever going to change it.

**Pull request closed without merging**
