### PR TITLE
Pylon Weight Changes

### PR DESCRIPTION
**Pull request by jezzaindahouse**
Max plz

We should mumble sometime today and talk over these things <3

### CODE REVIEW

**Comment by Diet-Cola** [comment]
How much faster is xp production with this?

**Comment by jezzaindahouse** [comment]
Advanced has old expert amount (10phr) and expert is now 15phr (from 10)

**Comment by Maxopoly** [comment]
Did you adjust the T2 to T3 ratio? Probably wont be on mumble before the weekend.

**Comment by jezzaindahouse** [comment]
Yes! There's now a good gap

**Comment by Maxopoly** [comment]
Or could you just list the new vs old weight, output and ratio?

**Comment by jezzaindahouse** [comment]
​*Basic Pylon*​
Old Ratio: 2 Weight = 0.125 Aether (per hour)
New Ratio: 2 Weight = 0.5 Aether (per hour)

​*Advanced Pylon*​
Old Ratio: 2 Weight = 0.53 Aether (per hour)
New Ratio: 2 Weight = 1.2 Aether (per hour)

​*Expert Pylon*​
Old Ratio: 2 Weight = 1 Aether (per hour)
New Ratio: 2 Weight = 1.5 Aether (per hour)

**Comment by Maxopoly** [comment]
And the total numbers?

 I feel like with this setup, both steps should be a 0.5 increase, especially because the T1-T2 gap is too big right now.

As a result of this, shouldnt xp recipes and repair recipes be updated as well? Also we should probably decrease the shard limit with this change.

**Comment by jezzaindahouse** [comment]
hmmmm lemme re-do the numbers another time

**Comment by ProgrammerDan** [comment]
Still arguing this inverts the intent of basic pylons for no good reason. They are now free with no cost overhead in terms of weight; yes less efficient but they don't "cut out" other producers with their presence, as intended.

I only support this pull for testing purposes, not as a final balance consideration.

**Comment by ProgrammerDan** [comment]
To expand briefly; the intent of basic pylons is a structure that is relatively inexpensive (but not cheap by any stretch) that isn't just inefficient in production, but inefficient in _consumption_ too, e.g. using a basic pylon hurts everyone else, too.

With this change, a basic pylon just hurts _you_, because you aren't getting as much Aether as you could if you upgrade. 

E.g. everything interesting about the basic and intermediate tiers from a shard-wide standpoint is now eliminated, and imho makes them non-compelling as a factory element.

I'd be okay with "shrinking" the size of the hurt (e.g. 20 weight instead of 40) but I do not support an elimination of the collective-hurt introduced by the basic pylon.

**Comment by jezzaindahouse** [comment]
So all pylons have a weight of 20? Would make it simple to understand and also a clear route to what is the most efficient.

**Comment by ProgrammerDan** [comment]
That's ... worse, still yet, based on what I'm saying, lol.

**Comment by jezzaindahouse** [comment]
rip

I'm not very good with this particular subject. I'll let someone else handle it for now :(

**Comment by Maxopoly** [comment]
I'm past the point where I really know what we want and what would be best inbetween what we discussed, Dan and what we've been forced into. No idea whether this is the right step or not.

**Pull request closed without merging**
