### PR TITLE
Minor fix to PrintUtils & a rogue typo

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Probably more I should be looking at, but fixed the PrintUtils typo outputting X,X,Z instead of X,Y,Z on locations.

### CODE REVIEW

**Comment by ttk2** [comment]
nice, Rourke can merge and it heads onto Civtest

**Comment by ttk2** [comment]
on civtest

**Comment by ProgrammerDan** [comment]
Just created a Diamond Axe Smithy at -5032, 70, -53 @ 10:49pm EST -- any confirmation?

**Comment by erocs** [comment]
2015-03-22 22:53:41 [INFO] FactoryMod v1.0: Factory creation attempted: [ProgrammerDan UUID] at world (-5032 70 -53)
2015-03-22 22:53:41 [INFO] FactoryMod v1.0: Production factory created: Diamond Axe Smithy

**Comment by ProgrammerDan** [comment]
Perfect, thanks Erocs.

**Pull request merged**
