### PR TITLE
Quick fix for crates being stupidly slow

### PR DESCRIPTION
**Pull request by ProgrammerDan**
See: https://forum.civcraft.co/t/compacting-is-too-slow/577

### CODE REVIEW

**Comment by hlprimm** [comment]
THANK YOU

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
on civtest

**Comment by ProgrammerDan** [comment]
Tested recipe, works as expected. Is very fast. Produces crates. Doesn't require fences :)

**Comment by ttk2** [comment]
going online tomorrow morning then.

**Comment by ProgrammerDan** [comment]
Sounds great, I can hear the collective sigh of relief from the XP industry and the wails of those looking to profit from the prior inanity of crate creation already :D

**Pull request merged**
