### PR TITLE
1.8 meats

### PR DESCRIPTION
**Pull request by caveofwonders**
Added mutton and rabbit to the grill

### CODE REVIEW

**Comment by ttk2** [comment]
hey you need to sign the CLA head to this link and sign off. 

https://www.clahub.com/agreements/Civcraft/FactoryMod

Good work, just needs some quick review.

**Comment by caveofwonders** [comment]
All signed and ready to test

**Comment by ProgrammerDan** [comment]
For a simple change like this 3 commits is overkill; think you've got the gitfu chops to squash? If not, I'd be happy to do so for you. Credit will remain to you.

**Comment by caveofwonders** [comment]
This is my first day on Github, so I'd be happy to learn from a more seasoned gitfu master.

**Comment by ProgrammerDan** [comment]
ok just did it so I can instruct you.

Do the following:

    git rebase -i HEAD~3

in the editor that pops up, replace the second and third line's "pick" with "fixup". Leave the first line alone. Save the file and exit the editor. Sit back and watch. Now use `git push origin patch-1 --force`. Unless I'm mistaken, this pull request will auto-update with the change.

**Comment by ProgrammerDan** [comment]
Just realized -- are you using a local git client at all? If not, I literally just tossed a bunch of nonsense words at you. Sorry.

**Comment by caveofwonders** [comment]
Haha, you are correct. I'm not using a separate client, just the webpage. Installing GitHub for Windows for next-level copy pasting. Thanks, Dan!

**Comment by ProgrammerDan** [comment]
I don't think you can do squash through Github -- if you mean you're installing git for windows, that's awesome. Welcome to the big leagues, it's about to get real in here :). 

Don't be afraid to query me, either here or on reddit, if you run into problems. Git can be ... intimidating, at first. Again, I'm also more than happy to squash for you, if you get stuck or frustrated.

**Comment by rourke750** [comment]
Can you squash all my commits ;)

**Comment by jjj5311** [comment]
sign me up as well lol

**Comment by ProgrammerDan** [comment]
Sure thing baes, just show me where to start :)

**Comment by caveofwonders** [comment]
Woo! I did it :) I feel like a real lady now.

**Comment by ProgrammerDan** [comment]
Bravo! @ttk2 I haven't verified this locally, but visually it looks sound. Given the new/better startup error messaging in FactoryMod, should be easy to detect any recipes with bad inputs so this is safe for Testing.

**Comment by ttk2** [comment]
this is now on Civtest for testing, double check it and report back.

**Comment by caveofwonders** [comment]
Worked perfectly for me

**Comment by ProgrammerDan** [comment]
Seems to be back off civtest, or is it on the new civtest?

**Comment by ttk2** [comment]
once we have some documentation I can stage it for restart on Civcraft.

**Pull request merged**
