### PR TITLE
Add nflookup command

### PR DESCRIPTION
**Pull request by TealNerd**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
I believe the intent was to allow private netherfactories. Any method that exposes their exact location, regardless of the purpose, would make private nether factories impossible. I get what you're after and I don't blame you for wanting it, and this appears well coded, but I think it runs pretty far counter the purpose of the NF design.

**Comment by WildWeazel** [comment]
If it's just a command they can run at will, let them triangulate it themselves. No need to give out exact coords to narrow down the search.

**Comment by TealNerd** [comment]
Still no reason not to. All it means is they run the command three times instead of once and they still dont have to do any math because they could just make waypoints at the three locations and position themselves the appropriate distance between them

**Comment by ProgrammerDan** [comment]
I get where you're coming from, but there's some implied risk to the current searching behavior. You have to carry the full set of aspects with you, attempt to place a factory, and act on the new information, in order to "triangulate" or otherwise track down an existing factory. If you aren't careful, you could accidentally create your factory where you don't want it. Again, I feel this ambiguity is beneficially intentional. If the prevailing devgroup opinion is for more drama though, go for it :D.

**Comment by TealNerd** [comment]
Yeah i guess that's true. I want to get @ttk2 opinion though, not sure if he saw my comment in the changelog

**Comment by jjj5311** [comment]
not to mention the risk of running around with all of the aspects to do this

**Comment by TealNerd** [comment]
doesn't seem to really be that risky but i suppose so

**Comment by ttk2** [comment]
I would prefer if it was not possible to trivially locate nether factories.
But the risk of accidentally placing a factory is a little disturbing

**Comment by jjj5311** [comment]
factory to create nether factory price stick

**Comment by TealNerd** [comment]
Yeah we either need this command, or if you try to make one and can't it
should tell you where the other ones are

**Comment by WildWeazel** [comment]
Oh wait, is this only supposed to happen when you're trying to create a factory? The code looks like it's just a chat command to be called at any time. Also there's a typo "closes" in the command description.

**Comment by TealNerd** [comment]
yeah it's a command since it doesn't tell you when you create one, it only tells you that you need more aspects

**Comment by ttk2** [comment]
we don't want to just give out the location of factories though.

**Pull request closed without merging**
