### PR TITLE
Repair factory only

### PR DESCRIPTION
**Pull request by ProgrammerDan**
@ttk2 @erocs @ anyone willing to double check this

Anticipating you a bit perhaps. Here's JUST the repair factory balance fixes, including ensuring

* repair factory configuration is actually loaded by FactoryModPlugin

* Nether Factory is listed last in the enumeration as required by Rourke

Builds fine locally, would be good to fast track this to Civtest so we can get repairs online.

*this stuff is seriously improving my gitfu*

### CODE REVIEW

**Comment by ttk2** [comment]
Looks good. Will be testing as soon as I am home.

**Comment by ttk2** [comment]
merged, onto Civtest it goes.

**Comment by ttk2** [comment]
2015-06-14 15:39:32 [ERROR] Error occurred while enabling FactoryMod v1.4.0 (Is it up to date?)                                                       │························
java.lang.NullPointerException                                                                                                                        │························
        at com.github.igotyou.FactoryMod.managers.FactoryManagerService.initializeManagers(FactoryManagerService.java:70) ~[?:?]                      │························        at com.github.igotyou.FactoryMod.managers.FactoryManagerService.<init>(FactoryManagerService.java:54) ~[?:?]                                  │························
        at com.github.igotyou.FactoryMod.FactoryModPlugin.onEnable(FactoryModPlugin.java:184) ~[?:?]                                                  │························        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]                                 │························
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]                    │························
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]                   │························        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]                        │························
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]                     │························
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]                           │························        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]                           │························
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]                           │························        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]                        │························
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]                         │························
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]             

still getting this on Civtest.

**Comment by WildWeazel** [comment]
I found a few more things broken while fixing this. I thought berge had gotten it to start up but he said no. Might want to pull it for now until I can get a clean launch.

**Comment by ProgrammerDan** [comment]
Ahh, didn't see this until now, so ignore my new pull. Do you need any
assist, or fix is straightforward?  Sorry for not testing this more
completely locally, was exhausted from the mechanics of the patchwork pull
construction.

**Comment by WildWeazel** [comment]
It's not your changes, there are some errors from the branch.

**Comment by ttk2** [comment]
just keep me in the loop and tell me what you need.

**Comment by ProgrammerDan** [comment]
@WildWeazel That's a relief but I figured as much, just general offer to be useful, I can poke at it on my VM as well.

**Comment by WildWeazel** [comment]
If you want to figure out a fix for the compilation error that I accidentally left in NetherCsvReader, that might be the last major failure.

**Comment by ProgrammerDan** [comment]
Ok. I'm middle of work day so can't actively contribute code right now, but if this is still open evening EST I will tackle it; let me know if that timing works for you, or if you are in a position/desire to work on it before that.

**Comment by WildWeazel** [comment]
I'm in the exact same position :)

**Comment by ProgrammerDan** [comment]
:D Alright. I'll make a post here when I start working on it unless you've indicated you've started; sound good?

**Comment by WildWeazel** [comment]
binary semaphore, got it

**Comment by ProgrammerDan** [comment]
alright, I'm looking at it.

**Comment by ProgrammerDan** [comment]
@WildWeazel enough has changed here I'm going to slow things up figuring out what's different. Not sure I see the reason for removing dependency on NetherFactoryManager yet. I'm going to keep looking at this but it'd be best if you took lead on the break fix.

**Pull request merged**
