### PR TITLE
 Flooring clay balls to blocks. Added brick_block to kiln. 

### PR DESCRIPTION
**Pull request by hlprimm**
Flooring change is just another extension of this pull: https://github.com/Civcraft/FactoryMod/pull/71

Kiln only currently makes individual bricks, which has no other use than making flower pots. Left that individual brick recipe in because I'm not sure if it serves any other purpose. 

However, I added brick_block recipe, which is what most people want when smelting clay for brick.

### CODE REVIEW

**Comment by ttk2** [comment]
this looks good. Its on civtest, run it and make sure it works.

**Comment by hlprimm** [comment]
@ttk2 Flooring works great. 

*BUT:* Kiln doesn't work! Only sees input of the recipe. So it'll consume two stacks of clay and make nothing. Looking at the config, everything looks tidy to me, but maybe I missed something in the syntax?

**Comment by ttk2** [comment]
Maybe it's an issue with some other part of the config? Does the existing recepie work on Civcraft?

**Comment by ProgrammerDan** [comment]
Just checked the startup logs, BRICK_BLOCK is not a valid material. Recipe is disabled.

**Comment by hlprimm** [comment]
@ProgrammerDan Dang. http://minecraft.gamepedia.com/Bricks shows it as brick_block

I'm not sure what those logs are from (factorymod on startup?), but surely it's not a upper/lowercase issue?

**Comment by ProgrammerDan** [comment]
Yeah I added verbose output on recipe read for factorymod startup to find non-obvious errors like this. Check bukkit for the name, the MC name doesn't actually matter to Bukkit.

**Comment by ProgrammerDan** [comment]
@hlprimm might be just BRICK: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#BRICK

**Comment by hlprimm** [comment]
@ProgrammerDan Ah, I didn't know that. I hope that isn't the individual brick needed to craft a brick block. There's a CLAY_BRICK, so maybe it is BRICK. I'll do a new commit and we can try it again. 

Thanks

**Comment by ProgrammerDan** [comment]
Change is on test, no startup errors at least!

**Comment by hlprimm** [comment]
Works great! 

bricks

**Comment by ProgrammerDan** [comment]
Glorious! This should be good to go, then.

**Comment by ttk2** [comment]
merged, staged for Civcraft

**Pull request merged**
