### PR TITLE
#46 factory logging enhancements

### PR DESCRIPTION
**Pull request by WildWeazel**

### CODE REVIEW

**Comment by erocs** [comment]
Ooooh yeah.

[INFO] FactoryMod v1.0: Factory creation attempted: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx with group xxxx at world (-178 -178 5)
[INFO] FactoryMod v1.0: The factory could not be created: §cNo factory was identified!

[INFO] FactoryMod v1.0: Factory creation attempted: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx with group xxxx at world (-178 -178 5)
[INFO] FactoryMod v1.0: Production factory created: Carpentry factory

So if I break the factory blocks, nothing is reported. I assume that puts it into some form of repair state? If so having that logged would be nice. I'm not sure how to actually destroy a factory once the blocks are broken...

**Comment by WildWeazel** [comment]
Ok I'm a little confused. I just tried it and apparently breaking blocks only sets repair to 0 but doesn't actually destroy it - I could replace any one of the blocks and it started acting like my (disprepaired) factory again. The code I added logging to seemed to show that breaking any block immediately removed the factory. I'm not sure how it's supposed to work but either way it should have at least logged "Factory block broken: ..."

**Comment by WildWeazel** [comment]
Went over the code again: the "destroy" method actually disrepairs it, while the "remove" is only called if destructible factories is enabled (our config doesn't set it). So it won't actually destroy the factory but it should still be logging the block break.

**Comment by WildWeazel** [comment]
@ttk2 verified that block breaks are logged. I will fix the location formatting on that and also add a log to Factory.destroy() that it was disrepaired since that step manipulates the factory directly instead of going through the respective manager.

**Comment by ttk2** [comment]
sounds good, thanks.

**Pull request merged**
