### PR TITLE
Adjusted XP recipes for RB changes

### PR DESCRIPTION
**Pull request by Goldmattress**
Adjusted XP recipes for RB pull request #51 https://github.com/Civcraft/RealisticBiomes/pull/51

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
yaml looks good

**Comment by ttk2** [comment]
So does this just divide requirements by 12?

**Comment by gipsy-king** [comment]
Yes

**Comment by Goldmattress** [comment]
16

**Comment by DoctorCelebro** [comment]
Shouldn't the requirements be divided 24 since the growths times got multiplied by 24?

**Comment by ttk2** [comment]
if yall thinks this is the right ratio get it on Civtest and get some testing done, we can roll it into production soon.

**Comment by ttk2** [comment]
@goldmattress so whats going on here? Should I just merge this and roll it online? Does it need testing?

**Comment by Goldmattress** [comment]
It was not it's fixed now, all requirements are reduced by 16x and in the RB pull speed is reduced 24x
Given the greater potential for production with a single account now I believe this to be a balanced change.

**Comment by Goldmattress** [comment]
And yes there is basically no point in testing, this is numbers change not any sort of recipe changes or rejigs.

**Comment by ProgrammerDan** [comment]
Agreed, I have no objections to immediate merge and deploy.

**Comment by ttk2** [comment]
very well then, it can go online Tuesday when I can oversee it and do some community management for it.

**Comment by hlprimm** [comment]
So is it better to just not make any XP until Tuesday?

**Comment by ttk2** [comment]
well yes.

**Pull request merged**
