### PR TITLE
1.2:1 ratio on diamond extraction, as requested.

### PR DESCRIPTION
**Pull request by GopherAtl**
I'm sure I'm misunderstanding something about your request, though. If so, sorry for wasting yer time?

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@Maxopoly given the "continuous" nature shouldn't these recipes be lowest common denominator with  appropriately reduced running times?

E.g. 1:1.2 -> 5 d ore in, 6 d out w/ running time 1/4 of current (allowing for at least one fuel consumption period) so let's call it 3s?

**Comment by GopherAtl** [comment]
Oh, follow-up thought, stacks as input size has the virtue of being efficient with slots - one proc of recipe automatically clears a slot in the chest where outputs can go. Finer level recipes would have *slightly* reduced capacity potential without overflowing the chest.

**Comment by ProgrammerDan** [comment]
Hmm, that's not a big concern IMHO b/c factories nicely shut off when full without destroying any input. So use a Pipe to extract outputs and a Pipe to inject input and you could run this forever, regardless of batch size -- but small batches means the little guy isn't cut out of the loop. :shrug:

**Comment by Maxopoly** [comment]
That batch size is fine imo, but I'm not opposed to a different one. If this recipe wasnt already enabled previously, there is also another error though.

**Comment by ProgrammerDan** [comment]
:shrug: Don't want to hold up the works. I'm a fan of lowest-common denominator because bless you maxopoly we finally can do it, but I don't care enough one way or the other besides mentioning it for thought here :)

**Comment by GopherAtl** [comment]
Poked around to see if I could spot anything that would be causing them to still be disabled... all I've found at this point is a case mismatch in the name, it's defined with name "Gem Extractor" and the upgrade references "Gem extractor." The other recipes around it appear to match case, so fixed it. Dunno if that'll fix the real issue.

If I'm going to keep tweaking this, I'm gonna have to get my own build environment set up again... :shudder:

**Comment by Maxopoly** [comment]
Yeah, it's case sensitive, that should fix it.

**Pull request merged**
