### PR TITLE
Fix for a bug with removing recipes

### PR DESCRIPTION
**Pull request by BlackXnt**
This fix should allow players to craft stone bricks.

### CODE REVIEW

**Comment by rourke750** [comment]
Did you test this?

**Comment by BlackXnt** [comment]
No. The problem with getType() is that you get the raw item without the durability. So we actually removed the first 3 recipes that return SMOOTH_BRICK instead of removing only the recipes  that return SMOOTH_BRICK with durability of 1,2 and 3.

**Comment by rourke750** [comment]
Good catch.

**Comment by BlackXnt** [comment]
So we don't have to remove the recipes of cracked stone and enchanted golden apple on humbug now. We should move everything to FactoryMod.

**Pull request merged**
