### PR TITLE
Squashed commit of the following:

### PR DESCRIPTION
**Pull request by jjj5311**
commit 7a3fb98b0246e663f2f521d7ce9f67fae1b9c5dd
Merge: 429d6c0 87b9dfa
Author: jjj5311 <jjj5311@gmail.com>
Date:   Thu Jul 30 11:44:49 2015 -0500

    Merge pull request #1 from jjj5311/patch-1

    Patch 1

commit 87b9dfa701174a7ebc4cd5475f1c006a317eb618
Author: jjj5311 <jjj5311@gmail.com>
Date:   Mon Jul 27 10:10:34 2015 -0500

    remove anvil config stuff

commit 37129fa6d4cde7e69afb1cd7e731b16629959e7e
Author: jjj5311 <jjj5311@gmail.com>
Date:   Mon Jul 27 09:54:18 2015 -0500

    Update FactoryModPlugin.java

commit 2a9ff7e247e110d9315278594b2578bb9283f0ee
Author: jjj5311 <jjj5311@gmail.com>
Date:   Mon Jul 27 09:15:00 2015 -0500

    Delete old anvil fix

    Fix Issues #126

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks good.

**Comment by ttk2** [comment]
so merge then?

**Comment by ProgrammerDan** [comment]
Looks good, yeah.

**Comment by ttk2** [comment]
what do I do with the config containing the no longer existing setting, will it cause an error if we still have it?

**Comment by ProgrammerDan** [comment]
nah, it's safe to leave in. Remove it at your leisure. Additional sections are ignored if not read.

**Pull request merged**
