### PR TITLE
Adding Charcoal advanced recipe

### PR DESCRIPTION
**Pull request by Vastitas**
Noticed there wasnt a defined recipe for this, added something so that it would atleast be visible within the GUI.

### CODE REVIEW

**Comment by Maxopoly** [comment]
It will be impossible to run this unless you add it to a factory

**Comment by Vastitas** [comment]
it is part of the coal burner factory

**Comment by Maxopoly** [comment]
Oh yeah, right. If you scale it down to factor 2 and up production time to 16s it's fine.

**Comment by Maxopoly** [comment]
Replaced by https://github.com/Civcraft/FactoryMod/pull/179

**Pull request closed without merging**
