### PR TITLE
I hope you see reason

### PR DESCRIPTION
**Pull request by Goldmattress**
Civcraft is the best server I have ever played, the people I’ve met, the experiences I’ve had are unlike any other I’ve ever had in a multiplayer game, the environment the developers and admins have created is a fantastic community of ~~autists~~ players. These fun times are exploring, building, traveling, talking, trading, warring, policing, state building, making things with tools I acquired through an economy designed to reward effort and efficiency with more spare time to do what is fun. The current system does not allow this civcraft to exist.

It’s civcraft not poverty craft, players should be able to use advanced tools and not have anxiety about the hours of work required to replace them if they efficiently and effectively replace them.

On the other hand players should not have everything given to them and factories should represent milestones in development for cities and important investments that yield good but reasonable returns. 

These capital investments should be materials that players can gather in reasonable amount of playtime and should not be materials that are not available to players or are impossible to gather by determined effort. 

The current system is none of these things, you need 600+ man hours to make the diamond ore extractor pay off, over a thousand iron picks to make it worthwhile to make the factory for them.

Reinforcements are just plain strange with alternating names, weird material requirements and a simply bewildering array of requirements. As an example a stack of the best reinforcement will require 8 factory operations in minimum and 192 ghast tears, 12 wither skulls,  384 diamonds, 384 lapis, 2302 slime(not spawning atm), 6912 coal ore, 864 blaze rods, 864 flint(Y?)  1728 iron, 8192 spider eyes, 16384 rotten flesh, 13824 granite, 27648 stone(these numbers were done in my head no hate plz). This is all despite the fact that all these resources are far harder to acquire than in 2.0. This is patently insane.

There are good segments with in the config. By example the enchantment system currently appears fair and balanced. However no one currently knows for certain given that no one has yet used the enchanting factory in any real amount. 

This is my drop in the bucket to help make civcraft fun.

### CODE REVIEW

**Comment by Goldmattress** [comment]
This is not a prefect pull but you can start form here and improve on this trainwreck, but ignoring the issue will not make it go away and pretending that making everyone poor is simulating social development is just cruel to a playerbase that wants to play a fun engaging game not a skinner box.

**Comment by ProgrammerDan** [comment]
At no point have _any_ of us indicated we are ignoring _anything_. 

At every point we've patiently and consistently indicated we are watching, measuring, and preparing a set of changes.

Willfully ignoring the things we ARE saying helps nothing.

-----

We'll review this new pull although it would have been best to simply update the prior one so we could see specifically which comments were addressed.

**Comment by Goldmattress** [comment]
> At every point we've patiently and consistently indicated we are watching, measuring, and preparing a set of changes.

It has been 5 days of nothing, I re wrote the entire FM config once in 4 hours, at least acknowledge the issues. I'm not saying you've ignored the complaints I'm saying you haven't addressed them.

**Comment by ProgrammerDan** [comment]
We've been fixing inventory wipes, random disconnects, and other seriously bad shit. 

Yet everyone is annoyed we haven't rebalanced factories that aren't going to be accessible for another several days / weeks anyway?

We're working off a priority burndown list.

I type quickly.

**Comment by Goldmattress** [comment]
Dan, I can do this quite easily, this is not an issue that senior devs need to do, I need dierction and I can re do the thing in an evening quite easily, help exists all you have to do is ask and actually take it.

This problem is not with factories that are weeks away it's tools that people should be getting in the first hours of play, you can't genuinely expect people to way weeks to use iron tools? And actually at this rate it's more like months of mining to get to iron tools.

This is near as a big a problem as those, it's not just a random problem for some people it's problem all the players have to deal with all the time, it make the server near unplayable due to the slow pace of play.

**Comment by ProgrammerDan** [comment]
It's more about modmail volume at the end of the day; inventory wipes, randomspawns, those generate massive headaches and overheads due to constant modmail volume.

But yes you are correct and there are additional steps underway to address the early-game difficulty as relates to tools, but it doesn't involve factories :).

I should be making a post about it soonish (day or two).

We tried giving some direction in the other PR -- for instance, the non-exponential increase of outputs for higher tier factories -- so hopefully that gives some good hints in terms of where we want this rebalance to move.

I can't comment further until I review this PR :).

**Comment by Goldmattress** [comment]
> We tried giving some direction in the other PR -- for instance, the non-exponential increase of outputs for higher tier factories -- so hopefully that gives some good hints in terms of where we want this rebalance to move.

I don't really understand what that means, returns on investment(marginal return) are by definition exponential. 

IMO the best fix is increasing ore drops and making it clear where the good rates are and dropping the weird requirements like anvils and buckets from factories.

Also the reinforcement system is needlessly complicated and anything beyond bracers is actually useless. you need more materials to make a small vault with them than was gathered on all of 1.0 and 2.0 combined.

**Comment by ProgrammerDan** [comment]
So a few examples of "exponential return":

furnace yields 1:1 ore to ingot
basic factory yields 1:2 ore to ingot
intermediate factory yields 1:4 ore to ingot
advanced factory yields 1:8 ore to ingot.

"linear return":

furnace yields 1:1 ore to ingot
basic factory yields 1:2 ore to ingot
intermediate factory yields 1:3 ore to ingot
advanced factory yields 1:4 ore to ingot.

"sublinear (optimal) return":

furnace yields 1:1 ore to ingot
basic factory yields 1:1.75 ore to ingot
intermediate factory yields 1:2.2 ore to ingot
advanced factory yields 1:2.4 ore to ingot.

So there's motivation to upgrade, but it's not overwhelmingly more productive then everything else; it's a clear winning advantage, but doesn't completely lock out everyone. Adjust figures ofc to match overall balance targets, and scale upgrade cost to yield a positive ROI after a sensible number of uses (20-50, depending on batch size could be less). Etc.

**Comment by Goldmattress** [comment]
But most of the stuff only has 1 or 2 recipes, the space for doing linear returns is small.

Also calling it "locking everyone out" is really weird, factories are open to everyone, the economy is not zero sum you don't take anything away from other people by being more productive.

**Comment by ProgrammerDan** [comment]
Factories are very vulnerable right now. Break all three blocks and the creation costs drop. 

Would you make your gem extractor fully public, knowing that? :P

It's the monopoly lockout problem, if you do linear it can be okay, but super-linear results in folks who've made the investment being so massively productive that they can completely suppress new entrants by devaluing goods (literally making it hard for people to get to their level, etc) -- we've seen that before (botting, etc.) ... not inventing any new theory here although I don't seem to be understood well, apologies if its my choice of diction.

**Comment by Goldmattress** [comment]
That's only the case if you have an effective method of preventing entry to the market, there is none right now. Actually having the creation costs so high makes the problem of locking out far larger by creating larger barriers to entry. 

Also the market is not efficient on civcraft just because someone made a factory that makes a good does not mean everyone has access to that good at the equilibrium price, there is always a large incentive to make your own factories as well from a political and game play perspective, you want factories because that's how you play the game and you want to them so you don't need to depend other people.

**Comment by ProgrammerDan** [comment]
Needing other people is explicitly a design goal this iteration. We can't mandate it, but we can make it difficult, so that's what we're doing. Attempting another balance point is just a full reversion to 2.0 end game.

**Comment by ribagi** [comment]
The problem is in most cases it is irrational to go for many higher end recipes even with groups 60+.  The goal blinds you from reaching the goal. If you really want to take a totalitarian game design methodology you will only find bad results in the end. Hell, the Config isn't even finished yet all the Devtators act as if it is the gold standard of game design. ¯\_(ツ)_/¯

**Comment by ProgrammerDan** [comment]
@ribagi Please read above:

> At no point have any of us indicated we are ignoring anything.
>
> At every point we've patiently and consistently indicated we are watching, measuring, and preparing a set of changes.
>
>Willfully ignoring the things we ARE saying helps nothing.

None of us are acting like it's a gold standard. We just want some careful thought given to the changes, that's all. Not saying Matta _hasn't_ done that, but it _is_ why we haven't made changes willy-nilly to date.

**Comment by erocs** [comment]
Saw the title. Why is there drama in the repository? Take it to the developer forum. https://forum.civcraft.co/c/development/lounge

**Pull request closed without merging**
