### PR TITLE
Recipes for Smooth Double Stone Slab and Smooth Double Sandstone Slab

### PR DESCRIPTION
**Pull request by auxiliary-character**
See [reddit thread](http://www.reddit.com/r/Civcraft/comments/30mjqw/suggestion_a_couple_of_blocks_that_would_be_nice/).

### CODE REVIEW

**Comment by rourke750** [comment]
@ttk2

**Comment by ttk2** [comment]
merge and put online. This is a jar update right?

**Comment by WildWeazel** [comment]
just config

**Comment by drjawa** [comment]
Was the wiki updated to reflect these changes?

**Comment by WildWeazel** [comment]
We don't seem to have any of the crafting overrides in the wiki

**Comment by ttk2** [comment]
they should probably all be added.

**Pull request merged**
