### PR TITLE
update from master

### PR DESCRIPTION
**Pull request by WildWeazel**

### CODE REVIEW

**Comment by ttk2** [comment]
what does this include?

**Comment by ProgrammerDan** [comment]
Pretty sure this is all stuff that's already applied. Wrong button perhaps? It includes the wood potato nerf that was reverted, my factory location change that's already applied; new stone slab recipes already applied ....

**Comment by WildWeazel** [comment]
I'm just updating my branch

**Comment by rourke750** [comment]
@WildWeazel Are you handling this?

**Comment by WildWeazel** [comment]
yes I just have to do it manually

**Comment by ttk2** [comment]
so whats this for?

**Comment by ProgrammerDan** [comment]
I'm guessing @WildWeazel is using this to manually cherrypick merged commits from master into his dev branch?

I usually just rebase against current master before committing:

git checkout working_branch

git fetch civcraft-origin

git rebase civcraft-origin/master

git push developer-origin master --force

obviously I don't recommend this if more than one person is working in your fork, you'll probably have to do merge refactors instead of rebase.

**Comment by WildWeazel** [comment]
yeah just ignore this, I'll figure it out before I merge back

**Pull request closed without merging**
