### PR TITLE
Major Ore smelter overhaul

### PR DESCRIPTION
**Pull request by Goldmattress**
So Ore balance has not move one iota since the start of 2.0 and I think some things are due for a change, gold and lapis are excessively rare, my calculations point to at least half, probably more of the quartz in nether biomes being gone.

So to address these issues I've made some changes.

Added Industrial Ore refinery.
This factory is colossally more expensive than the other smelters and runs on coal blocks, it has access to more efficient ore recipes that require a lot more fuel to run than normal recipes and are more efficient, especially with rare minerals.

Tweaked fancy ore smelter and ore smelter. I renamed them and changed some costs around a bit and most recipes tweaked to be slightly more efficient, diamond excluded.

Fancy stone brick smelter rewamped. Added quartz and prismarine as costs to it, upped the stone cost a lot.

Added the new stones to it as well as the old stone recipe from the normal stone smelter. New stone recipes changed to be less quartz intensive and more cobble intensive.

Essentially the lack of veins for lapis, redstone and gold makes then very rare and something not worth mining specifically for, the slow but now increasingly obvious lack of quartz and iron veins is unbalancing the overall system and small redress there should keep the players from being completely starved of them.

So overall the new Industrial refinery increases diamond output by 17%, coal output by 31 %, iron output by 57 %, gold output by 129 %, lapis outout by 84 %, redstone output by 75 % and quartz by 100 %, but is relatively expensive.

The big ass expensive ore smelter is something I want to try out to see if people will actually make it, it's something everyone uses and it 100% pays off for any community of even relatively small size so I want to put more pressure on towns to keep their factories in order and to have them compete more on who has what.
Right now as long as you have a few basic ones and the ore smelter the rest like xp and redstone stuff are tangential and used by very few people.

If people want the new stone types to be as common as cobble then they can mine some cobble to make it...

### CODE REVIEW

**Comment by staygroovy57** [comment]
Looks pretty good matta. Glad you've been thinking to prop things in this direction.

**Comment by Goldmattress** [comment]
What would you say the current value in d is of a stack of gold blocks?

**Comment by Maxopoly** [comment]
20d/stack

**Comment by staygroovy57** [comment]
> What would you say the current value in d is of a stack of gold blocks?

I actually think that value is fluctuating a lot. In the last year it's been as low as 3d/stack and as high as 20d/stack. Given the recent changes to spawning and steady availability, I would think it's going to settle somewhere around 12d or so.

**Comment by brintonofarran** [comment]
So on Saturday ttk2 posted the ore refinery and new stone factory were going live after a day of comments. They don't seem to be live now, and I was curious when that was going to happen.

Also, I have a major issue with the ore refinery. If I'm reading the changes in the Github correctly, that being that a repair multiple of 10 means it takes ten times the specified repair inputs to repair from zero to 100%, it takes 30 diamond blocks to repair the refinery each month, that is, 270 diamonds per month. Also, it would take 270 each of iron, redstone, and gold, while taking 450 coal. I'm in a position to build one of these behemoths because I've done my share of ming while also maintaining a good balance of different minerals, but these repair costs are simply insane. Is it possible the materials should not be in blocks but rather just their ingot, gem, and lump forms? A little math shows that, just considering the diamonds along, I'd have to run 524 diamond ore per month through the refinery just to profit enough to meet the repair costs in diamonds, and the other minerals probably work out to nearly the same ratios.. This is completely unreasonable.

**Comment by Goldmattress** [comment]
524 diamond ore a month is not unreasonable for a group of 10+ players, I've done more in a day of mining.

**Comment by brintonofarran** [comment]
Thank you. Consider my snide reply to your reply in Reddit withdrawn. Have any idea when it might go live?

**Comment by ttk2** [comment]
when I am not crazy busy, maybe tonight depending on when I get out of class?

**Comment by staygroovy57** [comment]
@brintonofarran thanks for bringing the repair issue up, I wasn't aware of what this was, just took it as being the usual 10% because nothing was mentioned about this when the announcement was made. Will have to do the math to see if it really proves to be worthwhile as an investment. To me this sort of factory will only make sense with a much larger server population, TBH.

**Pull request merged**
