### PR TITLE
IOrefactor

### PR DESCRIPTION
**Pull request by WildWeazel**
integrating space code

### CODE REVIEW

**Comment by WildWeazel** [comment]
perhaps @CivcraftBot should mention that the build FAILED....

**Comment by WildWeazel** [comment]
test this please

**Comment by WildWeazel** [comment]
you're no help.

**Comment by WildWeazel** [comment]
test this please

**Comment by WildWeazel** [comment]
test this please

**Comment by ttk2** [comment]
What did this do?

**Comment by WildWeazel** [comment]
This is the file load/save sanity checking with error logs ( #11 ), some associated refactoring to reduce code bloat and improve maintenance, and general cleanup. It's not in master yet, just getting my branch ready.

**Comment by ttk2** [comment]
Cool

**Pull request merged**
