### PR TITLE
Fix for NF

### PR DESCRIPTION
**Pull request by BlackXnt**
Tested on my local server.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks perfect. It's what I get for writing code off the top of my head :D 

Thanks, @BlackXnt

**Comment by ProgrammerDan** [comment]
@ttk2 this is good to merge

**Comment by ttk2** [comment]
what does this fix?

**Comment by ProgrammerDan** [comment]
Allows NFs to be repaired. The earlier patch had a typo.

**Comment by ttk2** [comment]
ah, does this need testing?

**Comment by ProgrammerDan** [comment]
@BlackXnt tested locally, confirm?

**Comment by BlackXnt** [comment]
I tested it. This is good to go.

**Comment by ttk2** [comment]
its online.

**Pull request merged**
