### PR TITLE
Factory logging

### PR DESCRIPTION
**Pull request by WildWeazel**
and a bit of cleanup

### CODE REVIEW

**Comment by ttk2** [comment]
any reason why this is not merged yet?

**Comment by WildWeazel** [comment]
just that I haven't tested it at all but what else is new

**Comment by WildWeazel** [comment]
http://192.99.169.83:8080/job/FactoryMod-master/76/ to Civtest

**Comment by erocs** [comment]
Was this updated on CivTest?

**Comment by ttk2** [comment]
its on civtest

**Pull request merged**
