### PR TITLE
1.8 Changes

### PR DESCRIPTION
**Pull request by ribagi**
Added a new Xp Factories! The Emerald Xp Factory
Added factories for enchanting! Both mass and random enchanting.
Added De/Compressor
Re-balanced Wood, Iron, and Diamond Xp Factories.
Re-balanced Repair Factory Costs

### CODE REVIEW

**Comment by Akiyama64** [comment]
I like the repair factory more in this version because the bases are gone, and less gold and lapis is needed. 

After a tool is run through this factory, from what I've heard, it will take five levels of XP to repair the tool on the anvil (which is about 6 XP bottles). Assuming cost per emerald block of 4d, we have ((4/(9))/9)*6= 0.296 diamonds. It seems an XP bottle has 10 XP on Civcraft, so one would need about 255 XP bottles to repair a tool requiring 38 levels (our current cap). A repair on such a tool costs about 12 diamonds in XP. http://minecraft.gamepedia.com/Experience#Levelling_up

Let's see how good of an advantage this factory has over anvil use.

Start up costs: 8 stacks of coal blocks is about 80 diamonds, 16 lapis blocks is about 16 diamonds, and 32 gold blocks is at most 8d (depends on pigmen spawning). Total: 104 diamonds to start.

Processing: A half a stack of coal blocks is needed, and that costs about 5 diamonds. If the repair factory allows the remaining 53 slots to have items in it, the cost per run is 5/53 = 0.094 diamonds. This is a crazy assumption though.

Additional comments on processing: If someone would only use this factory for three E5U3 picks, the cost per run per tool is 1.67 diamonds. Therefore, gathering together friends for a repair party is encouraged, but trust and online status of people is an issue. 

Being realistic, there are often three E5U3 diamond picks per decent vault dig or big project. Say that a rich guy invests in this repair factory and he expects at least 5 runs on this machine. Then total costs are 129 diamonds. Cost per run is 25.8 diamonds. Cost per tool per run is 8.6 diamonds. Why did I assume three pickaxes would be at a dig? Because it was my experience at the Etherium moat dig that there were most often three people online working on it, and we used diamond pickaxes hard. 

The Cost per tool per run can get really, really low if you have enough things to repair, but that's a bad assumption to have. In the meantime, when diamond picks need their repair costs reset, miners want it reset right then. 

At the moment, this factory is an incentive to hoard a lot of E5U3 diamond picks so that you can use them hard during a dig, get high repair costs, and then reset all of them at once. This is with ONE person. We don't live online. Some even have jobs, and I'm not going to phone my friends or trust strangers on /r/civcraft to come online to the repair factory with blocks of coal and their tools, weapons, or armor. (I would want them to help pay for their repair reset, after all.)

The lower the lines go, the more unrealistic the benefits are. 

graphs

But there are some pros to this repair factory. Multiple sets of prot IV can be processed with swords. This seems to be a decent factory for repairing sets of armor and weapons because a single person needs to repair four or more items in a combat loadout.

Still, this factory is a bad deal for city projects where we are limited in tools and people and online time. I would not invest in this factory for my building project because it's unlikely that enough people would be online AT THE RIGHT TIME for a repair session. The cost per run per tool sucks, and it still sucks even if we ignore the initial costs. 

If I assume that I don't care about initial costs, then I have to be realistic here: The nearest factory's at least a kilometer away, over the sea. So I have to cross the sea, potentially in bad TPS while my boat explodes, and I have to have 32 coal blocks to fix my pickaxe. And I doubt there will be anyone in the area to share coal with who happens to have a item they need repaired.

In the above case, I paid 5d for the coal and saved about 6d since I didn't repair at Level 38. Eh, it's about the same as repairing at full cost in 1.7.10. Not worth having a factory, but it absolutely shows that I need to buy more E5U3 picks, a lot more for myself. Even if everyone's online with their diamond picks on a project, we're going to mine as fast as the slowest person due to this factory, and that's dull.

And why did you have to use coal? I have to mine or trade for that much coal now? Oh my gosh, just allow us to use charcoal as an alternative

**Comment by Akiyama64** [comment]
My suggestion would be a coal or charcoal cost per tool in the repair factory. Something like 10 to 20 coal or charcoal per tool would be better than 32 coal blocks for a lot of slots. 

The coal block recipe could have been used on a separate factory that is made to repair armor and weapons though. It's better suited for that.

**Comment by ribagi** [comment]
There isn't and OR in Factorymod, this is why only Coal is used and not Coal OR Charcoal.

I already have a changed version which has the cost are in the following:

```  costs:
    construction:
      Coal Ore:
        material: 'COAL_ORE'
        amount: 192
      Iron Ore:
        material: 'IRON_ORE'
        amount: 8
      Redstone Ore:
        material: 'REDSTONE_ORE'
        amount: 8
      Gold Ore:
        material: 'GOLD_ORE'
        amount: 16
    repair:
      Coal Ore:
        material: 'COAL_ORE'
        amount: 32
    recipe:
      Coal Ore:
        material: 'COAL_ORE'
        amount: 64
```

The Coal Ore might be tuned down, but the reasoning for the use of ores is for when players going mining can create one on the spot and repair their stuff more easier. I will send another pull later (Or maybe edit this one) tomorrow which other changes.

**Comment by Akiyama64** [comment]
I like this new factory with coal ore.

It requires special material, and it's cheaper than 32 coal blocks (which would have been annoying to gather for the mundane task of repairing one's tools). 

"but the reasoning for the use of ores is for when players going mining can create one on the spot and repair their stuff more easier"

Ah, that makes more sense. 

Also, this recipe is pretty neat since it's less expensive. Therefore, digging is less boring when E5U3 picks can be repaired and let them get back to that already boring activity without frustration turning them off. It also pushes people to repair as a group while not harshly punishing people because they're digging a giant hole by themselves while friends are at work or vacation (if they have any tools needing repairs at all!).

**Comment by ttk2** [comment]
Ok dropping in here, can't quite read all of this so far, but I get the gist, how is the new starting and repair cost Akiyama? You did a good analysis further up.

**Comment by GavJenks** [comment]
I do not agree with that analysis. The factory is SUPPOSED to be severely punishing to run 5 tools through it or whatever. That's why you don't run 5 tools through it. You work with your neighbors to run 53 tools through it. Thus, it rewards cooperation and punishes lone wolves.

You CAN run 10 tools through if you want, but you'll pay for your refusal to cooperate. The graph and analysis above simply confirms that the plugin does what it set out to do.

And yes, you could hoarde 50 tools for just yourself. That's fine -- that's again just an optional high punishment cost/tax on lone wolfing, paying the hundreds of diamonds for a chest of tools up front.

It's perfect as is, and changing it to be "X coal per tool for however many tools you want" completely ruins the whole point of the system that addressed ttk's desired goals.

**Comment by Akiyama64** [comment]
"Ok dropping in here, can't quite read all of this so far, but I get the gist, how is the new starting and repair cost Akiyama? You did a good analysis further up."

I like it.

"You CAN run 10 tools through if you want, but you'll pay for your refusal to cooperate. The graph and analysis above simply confirms that the plugin does what it set out to do."

Everything would be really good if cooperation could occur on such a scale. People usually own zero to two E5U3 picks, so I have to have at least five people come together with their tools and fuel for the recipe to do it well. On top of that, my friends are most likely not going to be online at the right time, and less likely to need tools repaired when I do.

It's really irritating to mine your tool down until you reach high repair costs. At this point, the miner knows that it's a bad idea to use public emeralds to reset repair costs, but he also knows it's a bad idea to run the repair factory while nobody else is online OR when nobody has tools to spare. Sure, he could run the repair factory and use the coal, but this would still be a bad choice because his offline friends are going to get angry at how much stuff he used. 

I brought up the Etherium moat dig because that was the best case of digging that I've done with others. Five E5U3 diamond picks at most were there. Most often three were there. Most often, I went to repair my pick by myself. If the costs of running the factory, and the costly repair factory was present at the dig, I would have had to wait for DarkJesus and Crad to wear down their picks, and that would be kind of annoying. DarkJesus paid people well for that dig, and only four people, including himself, cooperated to dig it. A tool repair factory should not assume there would be more than three people online because it's hard to pull off four or more people. When I imagine putting the original tool repair factory of this pull request in Etherium, I saw a lot of waiting, and the potential for workers losing morale.

For this reason, the original recipe that used 32 coal blocks to run the factory sucks for tools. It's a better idea for PvP gear since there are multiple pieces to a gearset. I liked a flat rate of coal per tool in a repair factory that only accepts tools (like 9 to 15 coal) because it takes into account the reality of how many people are online. However, a bulk factory for tools, and all the other things, could be used to encourage people to do a repair pool.

**Comment by rourke750** [comment]
@Akiyama64 You do realize that this factory does not repair tools.  What it does is reset the item's repair level to one to then be repaired in an anvil.  So you can still repair your tools, you just need a bunch of tools to be run at once to get that level back to one.

Every repair in the anvil will follow: first repair 1, then 2, 4, 8, 16, 32, unrepairable -> put in reset factory and repeat.

**Comment by GavJenks** [comment]
"My friends are most likely not going to be online at the right time"

What?

1) Build the factory in a room with a wall of chests on one side, lockers
for each participating person

2) Get enough people participating so that there's a run's worth of stuff
once a day or two.

3) Leave any broken tools in your personal chest for dropoff. There is no
reason why you have to be online or in the room together.

4) Periodically, a trusted factory manager who has master key group perms
on all the chests checks them and takes out any tools once there are enough
waiting, keeping track of which one belongs to whom (you could use renames
to make this very easy). You could even have comparators set up on each
chest so that there's a visual redstone torch indicator that tools are
waiting and you don't even need to check each one.

5) He/she runs the factory.  And then returns the tools to your cubby
lockers.

And I don't know why you're fixated on only E5U3 picks. The factory repairs
everything. I routinely repair my E5U3 picks, my E4U3 shovels, my axes,
people will want to repair armor, etc.

And yes, depending on whether you have a large enough or smaller group,
each person may need 2-3 tools to be able to keep working until a run is
made. If you have a very large group, you might not even have to do that.
It's an excellent system for precisely that reason: it scales smoothly to
tax people more or less depending on how big and how active of a group they
live together in. One person = you need a whole chest of personal tools.
2-3 people: you may need a dozen tools each to make it cost effective. 20
people: maybe just one or two backup tools. 35-30 people: don't even really
have to worry about that.

More and more smoothly cost effective for more cooperation, it's brilliant.

**Comment by GavJenks** [comment]
You can also choose, as you mentioned, to just run the factory without a
full load. Which also appropriately smoothly taxes people more or less
depending on how organized they re and how dense the population is.

So you have two options to choose to pay a tax for
impatience/convenience/small grouping, versus cheaper for organization and
large groups. Up front cost for backup buffer tools to work while the
repairs wait (cheaper long term, up front low-cooperation tax), and/or
semi-full runs (no large up front, a la carte low-cooperation tax)

**Comment by ribagi** [comment]
Alright, I just patched in the newer changes onto this pull.

**Comment by ttk2** [comment]
so whats the repair factory cost now?

**Comment by Akiyama64** [comment]
"You do realize that this factory does not repair tools. What it does is reset the item's repair level to one to then be repaired in an anvil. So you can still repair your tools, you just need a bunch of tools to be run at once to get that level back to one."

Hm, then that explains why the recipe cost seemed high. It makes more sense when I consider that there would be five anvil repairs between runs instead of only one.

I looked through Points 1 through 5 and I thought, "So what am I risking and what am I getting out of all this?" Actually, your plan could work, but you're expecting too large of a group that is active. Five people actually using the tools enough that they become way too costly to repair in one week? That's stretching our assumptions because of Civcraft's population, and we have to take into account how many picks they have (usually it's just one E5U3 pick), so I guess eight picks, max, among the five of them to share.  Let's look at the description you offered:

"One person = you need a whole chest of personal tools.
2-3 people: you may need a dozen tools each to make it cost effective. 20
people: maybe just one or two backup tools. 35-30 people: don't even really
have to worry about that."

Since there are most often 3 or less people working on a project enough to wear down tools, I guess they're going to have to get thirty tools together to make things ideal. Last time I've seen 20 or more people doing something, it was fighting, and it was happening because of dramatic events.

"And I don't know why you're fixated on only E5U3 picks."

Because we'd want the factory near a digsite for epic structures. Sure, people want to repair armor and other tools, but they're not going to go to the digsite, and the factory manager's not going to wait for them to get there because it's unlikely that anybody's going to ask for factory access at a time close to when tools are ready for repair.

The E5U3 the most important digging tool of all in Civcraft.

"So you have two options to choose to pay a tax for
impatience/convenience/small grouping versus cheaper for organization and
large groups."

Yeah, I'm going to have to go with the "tax" on small grouping. I want the factory, for a single item, to result in slightly better anvil mechanics than 1.7.10 for one item. It costs 5d to get 32 coal blocks usually, and I could get two emerald blocks in Civcraft during 1.7.10 with that many diamonds. Those emerald blocks repaired the diamond pick and then some. If the recipe was like 14 or less coal blocks, I would be fine with it.

It's still pretty dang neat to get a group that succeeds at a large tool pool. However, if, for a single tool in the repair factory, it's more expensive and TIME-consuming to repair than in 1.7.10 anvil mechanics, then players aren't going to appreciate it. They're going to complain on the subreddit about how repairing's worse in 1.8 even though you could group tools together for repairs. A better way to do it is to make the recipe marginally less expensive than 1.7.10 anvil mechanics for a single tool in the factory, and then greatly benefit people who pool tools in it for repairs.

**Comment by Akiyama64** [comment]
@ttk2 All three of the costs are below in the new change. Thanks, @ribagi I like it.

Construction
+      Coal Ore:
+        material: 'COAL_ORE'
+        amount: 192
+      Iron Ore:
+        material: 'IRON_ORE'
+        amount: 8
+      Redstone Ore:
+        material: 'REDSTONE_ORE'
+        amount: 8
+      Gold Ore:
+        material: 'GOLD_ORE'
+        amount: 16
     repair:
+      Coal Ore:
+        material: 'COAL_ORE'
+        amount: 32
     recipe:
+      Coal Ore:
+        material: 'COAL_ORE'
+        amount: 64

**Comment by ProgrammerDan** [comment]
This newest change set reduces the current-market-price to around 13.2 diamonds per repair factory installation. I imagine the true market price will go up as coal ore currently has very little trade-able value; this will change. I like the use of ore. Coal is renewable; ore is not. As such, I'd expect once normalized, the price will be about 16-20d per repair factory, and 1-2d per recipe run.

**Comment by MonsieurWTF** [comment]
I'm still writing up some more about the Exp factory idea mentioned on https://github.com/Civcraft/RealisticBiomes/issues/15#. Just curious if you guys have any links to reddit threads discussing the XP changes from enchanting bottles to Emeralds/Emerald blocks and the ingredients involved.

In addition, I was looking over the enchants. Not sure how I feel about the 1:1 Tool-to-enchantment ratios. The Sharpness 5 recipe alone is a bit of a silly, and should require at least 90 swords for 5 Sharp V's to mirror the path taken to go from Sharp I up to the Sharp V vanilla climb.

**Comment by GavJenks** [comment]
" I want the factory, for a single item, to result in slightly better anvil mechanics than 1.7.10 for one item."

I know you do. But that's not what ttk wants. He made it very clear when asked what he wanted out of this update as well as in his recent monologue that he does not want to just maintain 1.7.10 status quo forever and ever.

Watering down the factory recipe in this way would make it the status quo, which undermines the whole point of why it was commissioned.

"Since there are most often 3 or less people working on a project enough to wear down tools"

Whole towns and communities don't generally just work on one project at once... You three are digging a hole. 10 of you are lounging around chatting and stuff. Another three are building a farm. Another 3 are building a housing district. Another 1 or 2 are hunting griefers and getting their armor banged up, etc. 

If the advantage caps out at 3 people, then it would still be better than 1.7 / being able to scale costs per tool. But it would hardly be pushing things to "civilization" level incentives.

**Comment by MonsieurWTF** [comment]
Just as a quick note, turning 5 Diamond swords into 5 Sharp V swords is ignoring the process of converting 16 Sharp I's all the way up. If you assume at least a 12.5% inefficiency and lose 2 swords, that's 18 D Swords per Sharp V, so this version has a retention of 11.333 non-renewable diamonds per 7 E blocks on each sword (not including the ~3 blocks it takes to enchant all the way up), or 55.6 Diamonds for 35 Emerald Blocks. Looks like a fair trade until adding the fact non-renewable is always more valuable than a renewable material.

It should be modified from:

      Diamond Sword:
        material: DIAMOND_SWORD
        amount: 5
      Emerald Block:
        material: EMERALD_BLOCK
        amount: 50

    outputs:
      Diamond Sword:
        material: DIAMOND_SWORD
        amount: 5

to:

      Diamond Sword:
        material: DIAMOND_SWORD
        amount: 36
      Emerald Block:
        material: EMERALD_BLOCK
        amount: 10

    outputs:
      Diamond Sword:
        material: DIAMOND_SWORD
        amount: 2

**Comment by BlackXnt** [comment]
Why are the tools factories more expensive than the armor factories?

**Comment by MonsieurWTF** [comment]
Is there a particular reason Emerald is being disassociated from repairing tools?

**Comment by GavJenks** [comment]
@MonsieurWTF It isnt, the repair factory resets the tool's repair count. You then have to repair it on the anvil with emeralds (for cheap)

**Comment by ribagi** [comment]
@BlackXnt Why shouldn't it not be cheaper? It had less recipes.  On top of that, the tool fact cost the same as the weap and armor factories.

@GavJenks You are correct,  it resets the cost. To get the health of the item back to 100, you must use an anvil.

@MonsieurWTF The 1 item in to 1 enchsnted item out is an oversight.  I will adjust the numbers later.

**Comment by BlackXnt** [comment]
@ribagi Since when is the cost of a factory decided by the amount of recipes it has? It is decided by what it produce and prot is much higher in the tech tree than enchanted tools. One of the main goals for moving enchanting to factories when it was discussed a few months ago was making prot more expensive not tools.

**Comment by ribagi** [comment]
Ignoring the set up cost, prot itself is more expensive.

**Comment by BlackXnt** [comment]
That is because you are referring to a full set of prot. A single tool will cost like a single piece of prot. And even more if you take the factory cost in account.

**Comment by ribagi** [comment]
How many people will create a new factory each time they want a new tool?

**Comment by BlackXnt** [comment]
When the factory costs 1250 diamonds and you need to repair it every 28 days(is it going to be 10%?) you must take it in to account. 

Why not reversing the costs of the tool factory and the armor factory?

**Comment by drjawa** [comment]
https://www.clahub.com/agreements/Civcraft/FactoryMod

**Comment by drjawa** [comment]
You need to do rebase. Can't merge due to conflcits.

**Comment by kwizzlehazzizle** [comment]
Not sure if this is the right place to say this, but I think we should consider adding an XP cost to running the repair factory since xp costs become almost negligible (5 or so bottles) to repair after using the factory.  I mentioned this in the morning changelog here: http://www.reddit.com/r/Civcraft/comments/387i6y/morning_changelog_20150602/

**Comment by ttk2** [comment]
Running the factory should not be so cheap that you do not it rather than
repair. If thats true run costs need to go up

**Comment by hlprimm** [comment]
Can I add in UB3 to the sword factory enchants?

**Comment by MonsieurWTF** [comment]
Perhaps UB recipe should start at 1, and then be combined up to UB3

**Comment by MonsieurWTF** [comment]
I mean, either route works, as long as the UB3 makes sure to consume 7-8 Diamond swords to take into consideration the combining costs for the swords and the % chance for fail.

**Comment by ProgrammerDan** [comment]
@MonsieurWTF Maybe I'm too much of a tool nub, but I have never combined lower-UBs to achieve UB3; it's always a clever combine of other tool gens. Then again, I'm the fool who just does lvl 30 tool generation. But, it only took me like 45 diamond tools enchanted at lvl 30 to achieve 9 eff5 ub3 pickaxes (pre-enchanted changes, of course). And I've done approximately that ratio several times. 

I haven't seriously looked at the balance involved in the tool factories yet, but I'm not yet grasping the relayed intuition as described in this thread (and others).

**Comment by hlprimm** [comment]
What's the need in stacking from ub1? Seems inefficient. I've always just
enchanted at 30 also and gotten a few ub3s4 etc that I could combine with a
s4fa2 and so on. Now there's no way to get a ub3 without a random enchant
factory which seems... odd.

**Comment by MonsieurWTF** [comment]
@ProgrammerDan Yeah, I would have a more precise number for UB3, but because it has never been a standard enchantment for swords (only way you could have gotten it in the past is through UB books), I really can't comment too accurately on the amount of swords to destroy for getting 1 UB3. As long as it's made expensive enough via the Emeralds, having that 1:1 recipe sounds okay to me.

**Comment by ttk2** [comment]
this needs to be rebased and have a run cost for the enchantment factory that makes it cost feasible to not use anvils only when the chest is full.

**Comment by rourke750** [comment]
they can rebase without you closing it.

**Comment by ttk2** [comment]
discussion needed to be refreshed anyways.

**Pull request closed without merging**
