### PR TITLE
Bastion Recipe Nerf

### PR DESCRIPTION
**Pull request by Tarenaran**
Cuts the amount of bastions produced per recipe in half (16 bastions down from 32). This doubles the cost of bastions

### CODE REVIEW

**Comment by rourke750** [comment]
Why are you trying to break the game Greg. Just let everyone have a good
time.

**Comment by ttk2** [comment]
so this just reduces output?

**Comment by Tarenaran** [comment]
Yes

**Comment by rourke750** [comment]
@ttk2 Bump

**Comment by ttk2** [comment]
not sure after feedback, maybe.

**Pull request closed without merging**
