### PR TITLE
Add new permission system

### PR DESCRIPTION
**Pull request by Maxopoly**
Let's FactoryMod use the new functionality added with https://github.com/Civcraft/NameLayer/pull/191

Should be merged after the NameLayer PR is merged.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks OK although I'd very strongly recommend you update your auto format to use 120 char lines instead of 80, a lot of really weird line refactors in this commit.

**Comment by Maxopoly** [comment]
I tried, but even after completly removing the formatting rules, applying a new global default one and applying it specifically for the project, it would accept it. I'll have to take a look again at some point

**Comment by ProgrammerDan** [comment]
Yeah, def not a huge deal at this point. Do you use eclipse? I can export my custom one if you want.

**Comment by Maxopoly** [comment]
Yeah, I use eclipse. The issue isn't getting one, I was just too stupid to get it to apply.

**Comment by ProgrammerDan** [comment]
Ah, it can be a bit dodgy

**Pull request merged**
