### PR TITLE
Iorefactor

### PR DESCRIPTION
**Pull request by Valadian**
Merged Compactors and Repair Factories, full IO Refactor. Significant changes to architecture to make it cleaner and eliminate copy pasta of code.

### CODE REVIEW

**Comment by ttk2** [comment]
so this is just a big combination cleanup pull? Will this delay the 1.8 xp changes? I am happy to shove it through otherwise but might wait a couple of days if so.

**Comment by WildWeazel** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
@ttk2 haven't looked at it close enough to be sure but looks like some refactor of the XP changes would be required to split them out into different config files. Given the number of errors and regressions currently in play there might be a good thing overall.

**Comment by WildWeazel** [comment]
It failed in PersistenceFactory looking for CompactorCsvReader

**Comment by WildWeazel** [comment]
I haven't been following the XP changes. This has everything that is in the master plus Teal's compactors already merged with it. It looks like XP will be config only, in which case there will be no conflict between them, other than having more things to potentially break in testing.

**Comment by ttk2** [comment]
I don't want to move the target for them more than it already has. But I
also want to using the same compactor and if we get changes online this
will languish waiting for the changes to be converted. Should probably
merge it then.

**Comment by WildWeazel** [comment]
test this please

**Comment by WildWeazel** [comment]
On the other hand XP is mostly a balance issue, the only thing to test is essentially whether the yml is valid and produces the expected recipe. That's a one-pass test that someone could knock out in a few minutes. Maybe it should go in now, and then we can spend the weekend banging on this.

**Comment by ttk2** [comment]
Whatever you think is best.

**Comment by WildWeazel** [comment]
It succeeded. @Valadian you want to drop build 13 on bergecraft and see if it at least starts up?

**Comment by ProgrammerDan** [comment]
@WildWeazel  Total agreement, fix infrastructure first, XP and repair and other stuff is simply config. It's taking a while to get those configs "right" but once complete even a refactor is comparatively simple.

**Comment by WildWeazel** [comment]
I was suggesting XP go in first because it's easy to test and get out of the way. Do you think we should merge this one first? Is XP not ready yet?

**Comment by ProgrammerDan** [comment]
Ah, misunderstood you. 

I'm a backend guy, I believe you should shore up your foundation before replacing your kitchen. In this case, it's immaterial which goes first. XP is fine to go first, although unless the latest merge updates start addressing some of the holistic problems the testers have identified it's not ready.

**Comment by WildWeazel** [comment]
Alright, that makes sense. I'll merge as soon as @TealNerd signs the CLA.

**Comment by ProgrammerDan** [comment]
@ttk2 You okay with this? Figure it's your call in the end.

**Comment by ttk2** [comment]
It's just that I am getting really concerned with the xp delay.

**Comment by MonsieurWTF** [comment]
If it's an issue I can try and chip in some work on the XP config Pulls/testing on Civtest later tonight.

**Comment by ProgrammerDan** [comment]
@ttk2 Alright. If that's your principle focus, then much as it pains me, let's get XP online (Target: staged for Saturday morning's restart) and rebase this after that merge. 

@Valadian I'm happy to handle the rebase post XP, hate to think you've done this kind of rebase 2/3 times now.

**Comment by Valadian** [comment]
You don't need a debase if you do your merges correctly. Xp shouldn't be code changes, so there should be no conflicts.
On Jun 11, 2015 2:12 PM, Daniel Boston <notifications@github.com> wrote:@ttk2 Alright. If that's your principle focus, then much as it pains me, let's get XP online (Target: staged for Saturday morning's restart) and rebase this after that merge. 

@Valadian I'm happy to handle the rebase post XP, hate to think you've done this kind of rebase 2/3 times now.

**Comment by ProgrammerDan** [comment]
Gitfu hairsplitting. I'll use whichever tool (merge or rebase) fits the reqs at the time I do it, no worries.

**Comment by ttk2** [comment]
Actually now that I think about it, if this has the compactor I am asking the new XP setups to depend on something in this, that could get messy.

**Comment by TealNerd** [comment]
If an XP recipe needs compacted items they just need to say it should be
the item with compactor lore

**Comment by TealNerd** [comment]
Trav how do sign?

**Comment by ttk2** [comment]
click here to sign

http://www.clahub.com/agreements/Civcraft/FactoryMod

**Comment by MonsieurWTF** [comment]
@TealNerd Yeah, but then that would mean making every cauldron's recipes changed to the crates, and only those who own compactors or had access to them could use cauldrons.

**Comment by TealNerd** [comment]
No you don't need crates in the recipe. The compactor consumes a crate and
a stack of items and outputs one compacted item. If a recipe was going to
require a compactor it would have limited those people anyway so that's not
a problem

**Comment by ttk2** [comment]
The compactor consumes a crate? Do you make them with another factor?

**Comment by TealNerd** [comment]
I wasn't sure about balance for that and actually forgot. But yeah a crate
is just a configurable item, by default it's just a renamed chest with lore

**Comment by WildWeazel** [comment]
We can figure out configs after we know this more or less works. To the civ cave! http://civcraft.co:8080/job/FactoryMod-master/110/

**Comment by ProgrammerDan** [comment]
:D History honors the bold!

**Comment by ttk2** [comment]
nice, is the repair factory in the main repo right now? I want to try and push that out if I can, since the XP changes continue to devolve.

**Comment by ProgrammerDan** [comment]
@ttk2 note that the repair factor is in this config, but it has the AA_DIAMOND cost placeholder shit. Working on fixing now, but it's kind of messy; for some reason git considered this a file replacement and altered every line, which makes diffs VERY hard to read for this

**Comment by ttk2** [comment]
Oh drat. Sorry we could reverse the merge and try and fix that?

**Comment by ProgrammerDan** [comment]
I won't be able to look at this any further for the next 5-6 hours; I think the issue is simply that master did not have the updated repair costs.

I haven't looked into this closely, is Teal's general compactor compatible with the Crates in Ribagi/Matta's XP pull? Or would we be running two types of compactors? (general and nether)?

**Comment by ttk2** [comment]
I wish to have them make the xp pulls general compactor compatible. Right
now we would have two.

**Comment by MonsieurWTF** [comment]
I don't see a reason why there should be a Nether Compactor/Decompactor if there's already a General purpose compactor/Decompactor.

**Comment by ttk2** [comment]
That's why I wanted to get the general one in. Otherwise we would be stuck
with two if we had to keep the nethercompactor for xp. Now we can make the
pulls for new xp rely on the general one and be done with it.

**Comment by ProgrammerDan** [comment]
@ttk2 If matta doesn't want to be bothered I can work on making the Emerald Cauldron compatible with Teal's compactor.

**Comment by ttk2** [comment]
that would probably be good, but its back seat to getting repair working
for now.

**Pull request merged**
